### ISSUE TITLE
Building Layouts in Flutter: duplicate "Row with 3 children" image

### ISSUE THREAD

**Issue by darrencole** [flutter/website#1250] opened 2018-09-08 21:28 UTC
From URL: https://flutter.io/tutorials/layout/

Good Day,
In step 1, the image of the Title Section is repeated for no apparent reason. Perhaps this was an oversight.
Regards,

**Comment by chalin** [comment] 2018-09-08 22:02
Thanks for pointing that out. The source of the problem is that https://flutter.io/tutorials/layout/images/lakes-diagram.png contains essentially two images. My guess is that it shouldn't, but I'll let @Sfshaza confirm whether this was intentional or not.

**Comment by Sfshaza** [comment] 2018-10-02 03:57
Definitely not intentional. I (or someone) needs to crop that image.  :)

**Comment by chalin** [comment] 2018-12-06 17:41
Reassigning to self, given that I'm editing this same image for another issue.

**Closed** 2018-12-07 21:58 UTC
Labels: E0
