### ISSUE TITLE
[PAGE ISSUE]: 'Integrate a Flutter module into your Android project'

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#7196] opened 2022-05-25 21:44 UTC
### Page URL

https://docs.flutter.dev/development/add-to-app/android/project-setup/

### Page source

https://github.com/flutter/website/tree/main/src/development/add-to-app/android/project-setup.md

### Describe the problem

Screenshots do not apply - New Module wizard looks completely different.

### Expected fix

Flutter module should be an option

### Additional context

I tried electric eel and chipmunk

**Comment by danagbemava-nc** [comment] 2022-05-26 11:40
Closing this as a duplicate of #6905

**Closed by danagbemava-nc** 2022-05-26 11:40 UTC
Labels: in triage
