### ISSUE TITLE
'Make authenticated requests' page issue

### ISSUE THREAD

**Issue by zxy888** [flutter/website#4485] opened 2020-08-14 09:16 UTC
Page URL: https://flutter.dev/docs/cookbook/networking/authenticated-requests.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/authenticated-requests.md

    final http.Response response = await http.get(
      url,
      headers: <String,String>{
        HttpHeaders.authorizationHeader:"Bearer " + token,
       },
    );
    print('response=' + response.body);

Description of issue:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid header field name, with 44
#0      IOClient.send (package:http/src/io_client.dart:62:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
#2      BaseClient.get (package:http/src/base_client.dart:27:7)
#3      get.<anonymous closure> (package:http/http.dart:46:36)
#4      _withClient (package:http/http.dart:166:20)
#5      get (package:http/http.dart:46:5)
#6      _MyAppState._requestList (package:flutter_abc/main.dart:22:42)
#7      _MyAppState.build.<anonymous closure> (package:flutter_abc/main.dart:40:15)
#8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
#12     B<…>

**Comment by sfshaza2** [comment] 2020-08-14 17:04
@domesticmouse, could you take a look?

**Comment by domesticmouse** [comment] 2020-08-17 10:10
I ran the following code in a new Dart project under Dart 2.9.1. This code is a lightly edited version of the complete example in the linked page:

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

Future<Album> fetchAlbum() async {
  final response = await http.get(
    'https://jsonplaceholder.typicode.com/albums/1',
    headers: {HttpHeaders.authorizationHeader: 'Basic your_api_token_here'},
  );
  final responseJson = json.decode(response.body);

  return Album.fromJson(responseJson);
}

class Album {
  final int userId;
  final int id;
  final String title;

  Album({this.userId, this.id, this.title});

  factory Album.fromJson(Map<String, dynamic> json) {
    return Album(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
    );
  }

  @override
  String toString() {
    return 'Album(userId: $userId, id: $id, title: $title)';
  }
}

void main(List<String> arguments) async {
  var album = await fetchAlbum();
  print(album);
}
```

**Comment by TheBiirb** [comment] 2020-08-28 09:25
The code looks fine to me. What do you think @domesticmouse ?

**Comment by domesticmouse** [comment] 2020-08-29 08:36
As far as I can tell, the cookbook code is working as intended.

**Comment by sfshaza2** [comment] 2020-09-11 07:51
Closing.

**Closed by sfshaza2** 2020-09-11 07:51 UTC
Labels: cookbook, e1-hours, p2-medium, waitingForCustomerResponse
