### ISSUE TITLE
Beta Channel last two versions (12b4727 @ 11/29/2023 and 0b591f2 @ 11/15/2023) has the same version and links on `Flutter SDK archive` page

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/website#9890] opened 2023-12-03 04:44 UTC
### Page URL

https://docs.flutter.dev/release/archive/

### Page source

https://github.com/flutter/website/tree/main/src/release/archive.md

### Describe the problem

The Beta Channel's last two versions (12b4727 @ 11/29/2023 and 0b591f2 @ 11/15/2023) has the same version and links: [3.17.0-0.0.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/linux/flutter_linux_3.17.0-0.0.pre-beta.tar.xz) and file https://storage.googleapis.com/flutter_infra_release/releases/beta/linux/flutter_linux_3.17.0-0.0.pre-beta.tar.xz.intoto.jsonl

In reality the 0b591f2 version was 3.17.0-0.0.pre, and the new 12b4727 version should be 3.17.0-1.0.pre.3?

Windows platform seems to be similar. Possibly other platforms as well.

### Expected fix

If the 0b591f2 version and links are correct, the latest 12b4727 version and links should be corrected.

### Additional context

I don't think I can fix it, I cannot find https://storage.googleapis.com/flutter_infra_release/releases/beta/linux/flutter_linux_3.17.0-1.0.pre.3-beta.tar.xz or https://storage.googleapis.com/flutter_infra_release/releases/beta/linux/flutter_linux_3.17.0-1.0.pre.3-beta.tar.xz.intoto.jsonl or variations

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by godofredoc** [comment] 2023-12-03 23:04
@CaseyHillers FYI

**Comment by CaseyHillers** [comment] 2023-12-04 18:18
The upstream issue is in https://github.com/flutter/flutter/issues/139311.

The way the website tracks releases is it looks at the [versions.json](https://ff100b61fdcbed0a9b073b431ef737f8f4b170f5871cd2d01910d22-apidata.googleusercontent.com/download/storage/v1/b/flutter_infra_release/o/releases%2Freleases_linux.json?jk=AanfhSDWB9jz1MR2zr4oeN2WfgrYdul38Xah5rCSW1qtchoXX5I3W0K5rT_rjuFqqdUTwh8ACxV0MPwIDXnJKM0chnfCI5kUQ02pHkP2nm40D77xXa9A1Bnft59Gq9pjDIf-i-bhko6yXBiGduF97TJFiRKv6Nz7qVXH5cBvqJS43EQzZK7dd9_5Fdy7NBphg5fuE0TonnWRG2wDbW24_YAI73l9dltF5xkfX0zISu1RKFw5hAqnXbyN-f7J-QArcBeoxxhnZV583Dfq5gIs36teiFMoYaInjqff7d5bQqwTrunGouk52LvL3izltWtpf-Vlhf2CTIlZvZW1TNAzY5_7xezPmBuLe4IraZbKFg1-yq5ClIO2F7i3qwjwLOYroiB0tBxwgKDdNlJJiSBBnu5PNmyxqQZB9BoD8GPBCeWImOJYdmdEYKL96-6ggNxjjoXgqQOlR1UbJGXmKxjMy3ixyXr5DnlaiBS7HU-7jFrJJr-Bp51De04k1vVwcHP3TPFn7URvD4bYTDPE07IFwY7Y3xKSoMbWQIKxA7IvvlPlPWKGMG-juowsrSrvyV_bte31x1zXDGVxxAlHbCJ2XH-ScrbcUd2GENR3SFEpaugX2-ZX_cm3HWcESIAB0ZcP1Y-2L2MZ6MUuAVYNb6LAAbOw6UUNSfCPNIMt_zeQfiDl_YrE0aweoNtrouFfQcYBoKy6P5Rn5rod_qOQzxvr_PVyMpOMdMcQDZWla58-nXF2PKKGM0K1ADPdrlhJePPA_G4CvAm1SRLFahKDkaSTVLwyBpRkzN4aBgRRH0hkQx77vT1-dWNtEuAy1-Jh7i1f9RFbDJkeG-Ag_aam6iUaJkiU5mbqpm5CsZISufUXPR5xB4aKtlEPJ6qdd7dSCJh2mpnZGrmHhwqp3O_7e7GcAtMydTEVkciQI2BTwIzVd4Yo_McEl2FbC4U2CZsSbPVYpFmXEnBLQxMTm3tni2gCcFgdXR-IMBlx4Sdx58D4sBHySVpYZFA0mNWuxkcibn996hBj1bp13uu59JGnHh1w5lHKnL6lds5KxX_iB0CenbOaZwOU2Cku8XSlqvYoi2u9uon4lRmk4Ce4u9OcSzHJTefA93YKmX8V3w-TKBqEO6J56EXI1zl13VrwrLP06HM8dV1YWCATFumUWGldvGe20HRfMqzoVD3I8Kkh70MwxsKx&isca=1)
 files. These are updated whenever we run packaging after the commit has been pushed to beta|stable. The issue is the tag metadata is pulled from the nearest commit, not the tag that's on the given commit. Ideally, this would've been an empty tag.

The culprit from the 3.17.0-0.1.pre release was we shipped it twice. Instead, we should've shipped 3.17.0-0.2.pre.

When we ship the next beta, this should resolve itself, and I've sent a PR to update the release infra to fail on this step explicitly before shipping it.

**Comment by parlough** [comment] 2023-12-04 19:48
Thanks for the explanation @CaseyHillers, I appreciate it!

I'm going to close this in favor of that upstream issue (https://github.com/flutter/flutter/issues/139311).

**Closed by parlough** 2023-12-04 19:48 UTC
Labels: p1-high, e2-days, cl.fixed
