### ISSUE TITLE
macOS development system requirement versions inconsistent

### ISSUE THREAD

**Issue by parlough** [flutter/website#10041] opened 2024-01-14 01:26 UTC
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/mobile-ios.md

### Describe the problem

The page says Xcode 15 is required for debugging code during Flutter development and that Cocoapods needs to be 1.12 or later.

However, currently on stable the `flutter` tool says [Xcode 14](https://github.com/flutter/flutter/blob/ef1af02aead6fe2414f3aafa5a61087b610e1332/packages/flutter_tools/lib/src/macos/xcode.dart#L23) and [Cocoapods 1.10](https://github.com/flutter/flutter/blob/ef1af02aead6fe2414f3aafa5a61087b610e1332/packages/flutter_tools/lib/src/macos/cocoapods.dart#L76-L77) are the minimum.

### Expected fix

I'm not sure where the minimums on the page came from, but I'm assuming they should match the `flutter` tool?

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment] 2024-01-14 01:45
@parlough : I'll double check with engineering. I believe I was going with latest. It's worth checking, though.

**Comment by parlough** [comment] 2024-01-14 01:49
Thanks for looking in to it @atsansone!

**Comment by atsansone** [comment] 2024-01-16 16:07
@parlough : I know why these show as Xcode 15 and CocoaPods 1.12. I was working from a "latest stable version" perspective, as you can see from [this archived version of the same page](https://web.archive.org/web/20230131020518/https://docs.flutter.dev/get-started/install/macos). CocoaPods didn't have a version listed, but I presumed that running `sudo gem install cocoapods` would install the latest version.

If this explanation works for you, close this issue. If not, I can discuss with @jmagman about using the minimum versions instead.

**Comment by atsansone** [comment] 2024-01-16 17:36
After discussing with @jmagman , I will close this issue. The minimum versions are what you found. We should recommend installing the latest stable.

**Comment by parlough** [comment] 2024-01-16 19:12
> atsansone can we change it to just "latest"? 

Yes please! I think especially since it's under "System requirements", not matching the actual requirement is a potential source of confusion. Also updating with each change would be painful too.

I think saying "latest" and relying on `flutter doctor` (which for sure has the up-to-date numbers for their SDK version) for any further diagnostics will be the most accurate while requiring the least maintainence.

**Comment by atsansone** [comment] 2024-01-24 19:27
@jmagman : We could make this change. Are there any circumstances where not having the version spelled out would occur? The point you raise here would only become more pronounced as versions update, that is, the difference between what the docs recommend and what the tool states. (I thought the issue there, btw, was that this page was intended for new installers who wouldn't have an issue with minimums.)

Please advise.

**Comment by jmagman** [comment] 2024-01-24 22:14
I'd be fine with saying Xcode and CocoaPods without specifying a version or saying "latest".  If developers don't have it installed, they will install the latest versions by default.  And if they already have them installed then the tool will complain the first time they try to use it and will prompt them to update.  

I also don't know why we mention git here
> [Xcode](https://developer.apple.com/xcode/) 15 to debug and compile native Swift or ObjectiveC code. The Xcode installation includes [Git](https://formulae.brew.sh/formula/git) 2.4 or later to manage source code.

**Comment by atsansone** [comment] 2024-01-25 00:57
@jmagman : We mention `git` because the VS code extension requires it. I've gotten errors from not having `git` installed as well. macOS doesn't include `git` by default, but Xcode does.

**Comment by jmagman** [comment] 2024-01-25 01:33
We can drop the git version then.  I don't want to need to notice and update our docs when Xcode revs the git version.

**Comment by atsansone** [comment] 2024-01-25 06:34
@jmagman That should work for macOS.

**Comment by anderdobo** [comment] 2024-01-26 19:08
The getting started docs are optimized for new installations, where we should guide to install the latest packages. This is separate from _minimum_ supported versions that the tool may enforce. We're specific with versions elsewhere in the getting started docs and I think we should stay consistent here, as long as we keep these recommended newest version numbers for new installations up to date. @atsansone and I discussed and aligned on this when we did the latest refresh of the docs.

**Comment by jmagman** [comment] 2024-01-26 19:14
> as long as we keep these recommended newest version numbers for new installations up to date

I don't keep track of when CocoaPods updates, or when a minor Xcode version comes out, or the version of git that it ships with.  If someone from tech writing wants to commit to keeping this version number up-to-date that's fine with me, though it seems inevitable someone will miss a version. I don't see what that buys us instead of saying "latest", if you must say something other than "Install Xcode".

**Comment by atsansone** [comment] 2024-01-29 20:21
This works for me. Closing this issue.

**Closed by atsansone** 2024-01-29 20:21 UTC
Labels: fix.bug, cl.wont-fix, a.get-started, p1-high, e1-hours, devos.macOS, from.team
