### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by JiDoc1234** [flutter/website#2436] opened 2019-02-22 22:11 UTC
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

![image](https://user-images.githubusercontent.com/810134/53274348-daa6ed80-36ee-11e9-9a10-3b5a1f162f46.png)

**Comment by sfshaza2** [comment] 2019-02-24 04:53
Need to see if we can replicate...

**Comment by sfshaza2** [comment] 2019-02-24 04:57
I left a comment on the other bug you filed, @JiDoc1234. Is this still happening for you?

**Comment by sfshaza2** [comment] 2019-03-06 05:22
Duplicate of https://github.com/flutter/website/issues/2460

Closing

**Closed by sfshaza2** 2019-03-06 05:22 UTC
Labels: needs-info, p1-high
