### ISSUE TITLE
[PAGE ISSUE]: 'Integrate a Flutter module into your Android project'

### ISSUE THREAD

**Issue by tstumpman** [flutter/website#8323] opened 2023-03-01 16:30 UTC
### Page URL

https://docs.flutter.dev/development/add-to-app/android/project-setup/

### Page source

https://github.com/flutter/website/tree/main/src/development/add-to-app/android/project-setup.md

### Describe the problem

Current version of android studio does not support adding flutter as a new module, and thus a module must already be created and added manually.

### Expected fix

Updated integration steps for latest version of android studio.

### Additional context

Android Studio Electric Eel | 2022.1.1

**Comment by danagbemava-nc** [comment] 2023-03-02 10:53
Closing this as a duplicate of https://github.com/flutter/website/issues/6905. 

See https://github.com/flutter/website/issues/6905#issuecomment-1414016353

**Closed by danagbemava-nc** 2023-03-02 10:53 UTC
Labels: in triage
