### ISSUE TITLE
[PAGE ISSUE]: 'Using memory wisely'

### ISSUE THREAD

**Issue by redx1t** [flutter/website#7390] opened 2022-07-25 06:10 UTC
### Page URL

https://docs.flutter.dev/perf/memory/

### Page source

https://github.com/flutter/website/tree/main/src/perf/memory.md

### Describe the problem

No detailed documentation on memory management

### Expected fix

A detailed documentation on memory management.

**Comment by danagbemava-nc** [comment] 2022-07-25 13:06
Closing this as a duplicate of #7369

**Closed by danagbemava-nc** 2022-07-25 13:06 UTC
Labels: in triage
