### ISSUE TITLE
Fix code examples on 'Hosting native Android and iOS views in your Flutter app with Platform Views' page

### ISSUE THREAD

**Issue by Yurssoft** [flutter/website#6444] opened 2021-11-05 12:46 UTC
##  Page URL

https://docs.flutter.dev/platform-integration/android/platform-views

## Page Source

https://github.com/flutter/website/tree/main/src/docs/development/platform-integration/platform-views.md

## Describe the Problem

 try following steps that are in code examples

**Expected results:** Code Works

**Actual results:** Code DOES not work. Example is not complete. No source code in github for example.

**Comment by danagbemava-nc** [comment] 2021-11-05 13:20
Hi @Yurssoft, which platform did you try to run on that didn't work for you?

**Comment by Yurssoft** [comment] 2021-11-05 13:29
iOS.
My point is more about suggestion to put source of this example to github, so everyone can run and see by themselves. Than it actually does not matter if example code updated itself. I can to example and see by myself.

Is it possible to include sections for `SwiftUI Views` also?

**Comment by danagbemava-nc** [comment] 2021-11-05 14:29
Oh, I see. 
Reading through the example itself, I noticed it is not "beginner-friendly". 
I suppose putting the example up might help beginners and also improving the documentation itself.

**Comment by Yurssoft** [comment] 2021-11-05 14:35
Yes)) For sure🙂
If it is possible, can you suggest document how to get dependencies not from cocoapods but fro swift package manager? I was unable to find any description how to do that🤷‍♂️

**Comment by atsansone** [comment] 2023-05-23 03:56
@parlough , did your work on https://github.com/flutter/website/pull/8089 fix this issue?

**Comment by leighajarett** [comment] 2023-10-26 16:02
Taking a look at this issue, I'm not sure I understand what's being requested. It seems like three things were mentioned:

1. Code not working -- it seems to work for me. What specifically is not working? Can anyone reproduce?
2. SwiftUI examples -- this is tracked [here](https://github.com/flutter/website/issues/8320)
3. SPM examples -- this is not yet supported, but when it is then we will add docs

If we can't reproduce 1, can we close this? @atsansone

**Comment by sfshaza2** [comment] 2024-07-30 01:00
Yes, let's close this.

**Closed by sfshaza2** 2024-07-30 01:00 UTC
Labels: act.question, p2-medium, st.blocked, e1-hours, st.triage.ltw, target.iOS, target.Android, from.page-issue
