### ISSUE TITLE
'Pass arguments to a named route' page issue

### ISSUE THREAD

**Issue by zzzh** [flutter/website#3842] opened 2020-03-24 06:40 UTC
Page URL: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigate-with-arguments.md

Description of issue:
Don't understand why onGenerateRoute way even exist, isn't it too tedious?
As I see, ModalRoute.of way is much esaier to use.

**Comment by micpap25** [comment] 2020-09-22 03:58
@sfshaza2 , what's your take on this? I feel the answer to the issue is to delete the section but is that necessary?
I'll put together a PR for this and you can close it if you feel this isn't needed.

**Comment by sfshaza2** [comment] 2020-09-24 21:15
As the Navigation system is about to change significantly, I would defer to @johnpryan on this call.

**Comment by johnpryan** [comment] 2020-10-05 18:14
`onGenerateRoute` is for more flexible route handling, since it can handle any route. Since this API hasn't changed with Navigator 2, this sample is probably still useful.

**Comment by micpap25** [comment] 2020-10-05 19:24
In that case, I think this can be closed, right?

**Closed** 2020-10-05 19:45 UTC
Labels: e1-hours, p2-medium
