### ISSUE TITLE
Building Layouts in Flutter: duplicate "Row with 3 children" image

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1916] opened 2018-12-06 13:26 UTC
@gggustafson commented on [Sun Jul 29 2018](https://github.com/flutter/flutter/issues/19957)

From URL: https://flutter.io/tutorials/layout/

The "Title Section" figure is duplicated.

---

@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter/issues/19957#issuecomment-444869762)

I assume you mean

![image](https://user-images.githubusercontent.com/405837/49586936-dd513c80-f962-11e8-886c-e6a95adba274.png)

where the first of them looks redundant.

**Comment by gggustafson** [comment] 2018-12-06 14:14
@zoechi The two are identical. The fix is to eliminate the first image.

**Comment by chalin** [comment] 2018-12-06 16:12
Duplicate of #1250.

**Closed by chalin** 2018-12-06 16:12 UTC
Labels: duplicate
