### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases'

### ISSUE THREAD

**Issue by IAmBotmaker** [flutter/website#6643] opened 2022-01-08 10:57 UTC
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

Stable channel (Windows):
Table of versions is duplicated twice - one duplicate inside the table - under the other one.

**Comment by IAmBotmaker** [comment] 2022-01-08 10:59
The same bug for Stable channel (macOS & Linux)

**Comment by domesticmouse** [comment] 2022-01-10 03:21
Screenshot showing the issue you are seeing would be helpful

**Comment by danagbemava-nc** [comment] 2022-01-10 13:18
Duplicate of #6329

**Closed by danagbemava-nc** 2022-01-10 13:18 UTC
Labels: needs-info
