### ISSUE TITLE
The tooltip on the website in First Flutter App Part 2 is too excessive

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1938] opened 2018-12-07 11:08 UTC
@usama8800 commented on [Sat Aug 11 2018](https://github.com/flutter/flutter/issues/20477)

In [Write Your First Flutter App, part 2](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2), anywhere I stop my mouse, a tooltip appears which is very annoying. 

The tooltip stops showing if I click my mouse once.
Then if I hover my mouse over something that has a tooltip, it starts appearing again wherever I stop my mouse 
Or if I scroll and then move my mouse

Also found the same in [From Java to Dart](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#0) so it seems to be a bug in that kind of steppers

Using Chrome Version 68.0.3440.106 64 bit

---

@zoechi commented on [Fri Dec 07 2018](https://github.com/flutter/flutter/issues/20477#issuecomment-417852976)

I can reproduce. 
When I tried the tooltip was following the mouse for several seconds.

**Comment by chalin** [comment] 2018-12-07 17:04
Thanks for reporting this issue @usama8800. It is a duplicate of https://github.com/dart-lang/site-www/issues/815. Please track resolution via 815.

**Closed by chalin** 2018-12-07 17:04 UTC
Labels: duplicate
