### ISSUE TITLE
Document flutter run / build --dart-define argument

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#5853] opened 2021-05-26 10:10 UTC
Yeah, this is a deficiency of our docs! `dart-define` is a way to pass compile-time variables to the `flutter run` or `flutter build` commands. I gather that you can even use it to pass values down to the native level. Please file a bug about this omission on the flutter.dev repo. In the short term, maybe provide a full example *or* link to the only page on the site where dart-define is used, [Report errors to a service](https://flutter.dev/docs/cookbook/maintenance/error-reporting).

_Originally posted by @sfshaza2 in https://github.com/flutter/website/pull/5839#discussion_r638845122_

**Comment by parlough** [comment] 2023-01-05 04:48
I'm going to close this as a duplicate of https://github.com/flutter/website/issues/4215. This still needs to be addressed.

**Closed by parlough** 2023-01-05 04:48 UTC
Labels: p3-low, e1-hours
