### ISSUE TITLE
Bug : There is a page UI issue

### ISSUE THREAD

**Issue by SAGARSINGH-1** [flutter/website#9487] opened 2023-10-06 16:17 UTC
### Page URL

https://docs.flutter.dev/get-started/codelab

### Describe the problem

When i pull down the page the scroller and links is above the banner.

### Expected fix

Solution the links and scroller should be hidden back in the banner.

### Additional context

<img width="970" alt="image" src="https://github.com/flutter/website/assets/81561733/3c0264fa-621b-477e-ab95-b4b6fcea2f58">

**Comment by danagbemava-nc** [comment] 2023-10-09 12:41
Hi @SAGARSINGH-1, what browser are you using? Is your internet connection strong? I'm thinking that your css styles may not have properly loaded.

Is this the only page you see it on?

**Comment by parlough** [comment] 2023-10-09 15:11
Thanks for reporting this issue and the extra information :) 

Closing as duplicate of https://github.com/flutter/website/issues/9000.

**Closed by parlough** 2023-10-09 15:11 UTC
Labels: st.triage.triage-team
