### ISSUE TITLE
we should update the hot reload documentation page to clarify some additional use cases

### ISSUE THREAD

**Issue by devoncarew** [flutter/website#2920] opened 2019-08-19 20:21 UTC
We should update the hot reload documentation page (https://flutter.dev/docs/development/tools/hot-reload#limitations) to clarify some additional use cases.

We recently hit an issue where a closure not reloading on hot reload caused user confusion. 
Changing the [TextStyle](https://github.com/InMatrix/samples/blob/master/veggieseasons/lib/styles.dart#L11) referenced in [this line](https://github.com/InMatrix/samples/blob/master/veggieseasons/lib/screens/list.dart#L64) is not reload friendly.

@sfshaza2 

also cc @InMatrix and @jacob314, who have more context on the issue hit

List of known limitations missing from the hot reload doc (updated on 2020-01-21): :
- Changing native code
- Changing code related to routing (The original post is an example. @goderbauer would know more.)
- Changing packages

Issues that need some investigation
- Reloading fonts and images (https://github.com/flutter/flutter/issues/49230)
- Additional limitations when using statement management packages (https://github.com/flutter/website/issues/3566)

**Comment by jacob314** [comment] 2019-08-19 20:46
Extra context:
A fix is to change the closure defined at [this line](https://github.com/InMatrix/samples/blob/master/veggieseasons/lib/screens/list.dart#L44) 
to a reference to an instance method in the class. Otherwise the closure fails to hot reload resulting in stale ui.

We should investigate whether const canonicalization in the CFE has made this case worse. It is possible that previously a style change like this would be reflected even if the closure wasn't reloaded.

**Comment by sfshaza2** [comment] 2019-09-17 23:39
@devoncarew @jacob314, I haven't addressed this bug because I'm not sure what to say. Can you provide some guidance?

**Comment by jacob314** [comment] 2019-09-17 23:56
@a-siva is there an existing doc from your team explaining the current limits of hot reload and the technical reasons behind them?

**Comment by a-siva** [comment] 2019-10-02 21:36
Most of what we had is documented here https://flutter.dev/docs/development/tools/hot-reload

**Comment by sfshaza2** [comment] 2019-10-02 21:56
Siva, this bug says that we should add to the page, but I'm not sure what we need to add. Can you read the original bug (above) and weigh in?  Otherwise, I can close this bug.  thx

**Comment by InMatrix** [comment] 2019-10-26 18:53
I created an example to reproduce the specific hot reload limitation we saw in the UX study in an issue filed against the framework: https://github.com/flutter/flutter/issues/43574

**Closed** 2020-05-01 19:04 UTC
Labels: e1-hours, from: study, p2-medium
