### ISSUE TITLE
[PAGE ISSUE]: 'Flutter architectural overview'

### ISSUE THREAD

**Issue by GKrstic** [flutter/website#7301] opened 2022-06-23 09:24 UTC
### Page URL

https://docs.flutter.dev/resources/architectural-overview/

### Page source

https://github.com/flutter/website/tree/main/src/resources/architectural-overview.md

### Describe the problem

Flutter official documentation is missing dark theme. Would be awesome if you added a functionality to switch to the dark theme.

**Comment by MiraMarshall** [comment] 2022-08-16 22:11
Closing, this is a duplicate of [issue #3632](https://github.com/flutter/website/issues/3632)

**Closed by MiraMarshall** 2022-08-16 22:11 UTC
Labels: duplicate, infrastructure, p2-medium
