### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by Tensa-K** [flutter/website#4031] opened 2020-05-02 22:57 UTC
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:

In the Step 1 chapter, a sub-step is missing : it is necessary to add the WelcomeScreen widget in the routes property of MaterialApp at the beginning with `'/welcome': (context) => WelcomeScreen()`.

**Comment by sfshaza2** [comment] 2020-05-04 13:38
Thanks, @Tensa-K!

**Comment by arps18** [comment] 2020-05-14 07:00
@Sfshaza Can I make the necessary changes?

**Comment by sfshaza2** [comment] 2020-05-14 15:58
Yes, of course, @arps18!

**Comment by arps18** [comment] 2020-05-14 17:34
@Sfshaza The issue seems already solved. I can't reproduce it!

**Comment by sfshaza2** [comment] 2020-05-14 18:13
!! Well, thanks anyway, @Tensa-K! Closing this issue.

**Closed by sfshaza2** 2020-05-14 18:13 UTC
Labels: codelab, e1-hours, p1-high
