### ISSUE TITLE
Flutter app running issues after install flutter.

### ISSUE THREAD

**Issue by rcsingh1234** [flutter/website#2123] opened 2018-12-27 11:08 UTC
Description: 

Error retrieving device properties for ro.product.cpu.abi:

Launching lib\main.dart on Moto G 5S Plus in debug mode...
Initializing gradle...
Resolving dependencies...
--------- beginning of main
12-27 16:34:59.508 I/EventLogSendingHelper(18067): Sending log events.
Unhandled exception:
Exit code -1073740940 from: C:/Android\platform-tools\adb -s ZY3227B4JT shell -x logcat -v time -t 1
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:353:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:284:10)
#2      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:504:27)
#3      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:678:41)
#4      _runGuarded (dart:async/stream_controller.dart:804:24)
#5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217:7)
#6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:817:19)
#7      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#8      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:242:71)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:285:5)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#11     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:387:62)
#12     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:438:26)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:820:20)
#20     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:436:15)
<asynchronous suspension>
#21     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:384:12)
<asynchronous suspension>
#22     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:289:38)
<asynchronous suspension>
#23     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#30     Future._complete (dart:async/future_impl.dart:476:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#33     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#34     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#41     Future._complete (dart:async/future_impl.dart:476:7)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#43     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by zoechi** [comment] 2018-12-27 14:30
Duplicate of flutter/flutter#16865

**Closed by zoechi** 2018-12-27 14:30 UTC
