### ISSUE TITLE
Incorrect Widget Catalog page and URL redirection

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1801] opened 2018-11-30 18:24 UTC
In a recent study, a participant visited http://flutter.io/widgets/layout/ from Google Search result, she was redirect to https://flutter.io/docs/reference/widgets/layout

If I understand current IA correctly, https://flutter.io/docs/reference/widgets/layout should not exist. Under Reference, it should be Widget Index, not catalog. This URL/page is not visible from left nav but is accessible from search result.

This deprecated URL (http://flutter.io/widgets/layout/) should redirect users to UI >  Widget Catalog - Layout (https://flutter.io/docs/development/ui/widgets/layout). 

cc: @jayoung-lee

**Comment by chalin** [comment] 2018-11-30 20:21
The problem is due to an invalid redirect, which is fixed by #1804.

Note that originally, _all_ catalog pages were in **two places** according to the IA (see #1425), and they still are, except that the **canonical path** for the **catalog** is `/docs/development/ui/widgets/catalog` (and when navigating from this path you stay under `/docs/development/ui/widgets/`).

Is that ok, or do you want me to remove the duplication?

**Comment by chalin** [comment] 2018-11-30 20:40
I've reopened this so that you can answer my previous question (https://github.com/flutter/website/issues/1801#issuecomment-443327934).

**Comment by galeyang** [comment] 2018-11-30 21:59
Thanks for fixing the redirection! 

For the current duplication, do you know if a user would see two Google search results linking to separate pages with the exact same content? This could be confusing...

Also, I found if users visit `/docs/reference/widgets/layout` from google search result and click the below link (linking to widget index), they may get lost and don't have a clear path on how to get back.
![image](https://user-images.githubusercontent.com/5102864/49316462-e5623580-f4a5-11e8-8118-6c40661d9f5d.png)

Does "having Widget Catalog under UI and the Widget Index under Reference" solve these potential problems?

**Comment by chalin** [comment] 2018-11-30 22:55
I've moved this thread to #1808.

**Closed by chalin** 2018-11-30 22:55 UTC
Labels: question, ux-research
