### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by AdrKacz** [flutter/website#6896] opened 2022-03-10 08:48 UTC
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

The link at : *In this example, connect to a [test server provided by websocket.org](http://www.websocket.org/echo.html).* returns **403 Forbidden Access**.

The URL [http://www.websocket.org/](http://www.websocket.org/) returns **200 > Service No Longer Available**.

### Expected fix

To have a valid URL. *I have no idea where to find such, neither what was the original ressource.*

### Additional context

*Thank you for your documentation 👍*

**Comment by danagbemava-nc** [comment] 2022-03-10 11:19
Duplicate of #6382

**Closed by danagbemava-nc** 2022-03-10 11:19 UTC
Labels: in triage
