### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by LeoBadeaux** [flutter/website#6857] opened 2022-02-28 12:53 UTC
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

This example uses an echo server provided by websocket.org. Recently, websocket.org has shutdown. This may not be a major issue, but the example needs to be rewritten to use a different echo server (if there is one).

### Expected fix

Rewrite to use a different echo server if available, or if there aren't any public ones, make a flutter echo server usable by everyone for this example.

**Comment by danagbemava-nc** [comment] 2022-02-28 13:11
Duplicate of #6382

**Closed by danagbemava-nc** 2022-02-28 13:11 UTC
Labels: in triage
