### ISSUE TITLE
'Build and release an iOS app' page issue

### ISSUE THREAD

**Issue by FlashJonas** [flutter/website#4297] opened 2020-07-02 12:30 UTC
Page URL: https://flutter.dev/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Description of issue:
Strange text artifacts "keyboard_arrow_down" shown vertically and horizontally on page in Safari on Mac OSX 10.15.5, 13.1.1
But not in Chrome!

<img width="2445" alt="screenshot flutter site issue" src="https://user-images.githubusercontent.com/3299910/86358853-7c8a0300-bc70-11ea-9b2e-02019aa09845.png">

**Comment by kwalrath** [comment] 2020-07-06 16:20
Someone else has reported a similar issue (caused by icons not loading): #4301

But it's working for me in Safari 13.1, macOS 10.15.4. And in Chrome, of course. I did see this quite a bit a few months ago in some Chrome pre-releases, but it's been fine for me lately. I think reloading was an effective workaround.

**Comment by FlashJonas** [comment] 2020-07-10 13:05
Yeah, revisiting this now and I can't reproduce it either.

**Comment by kwalrath** [comment] 2020-07-10 16:24
I'm going to close this, but will keep an eye out for it. Thanks for reporting it, @FlashJonas!

**Closed by kwalrath** 2020-07-10 16:24 UTC
Labels: can't reproduce
