### ISSUE TITLE
[PAGE ISSUE]: 'State management'

### ISSUE THREAD

**Issue by Leo-Chan01** [flutter/website#6971] opened 2022-03-29 17:32 UTC
### Page URL

https://docs.flutter.dev/development/data-and-backend/state-mgmt/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/state-mgmt/index.md

### Describe the problem

There is no data in this page.

**Comment by danagbemava-nc** [comment] 2022-03-30 11:35
Duplicate of #6758

**Closed by danagbemava-nc** 2022-03-30 11:35 UTC
Labels: in triage
