### ISSUE TITLE
JSON serialization code example outdated

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1545] opened 2018-10-25 08:39 UTC
https://flutter.io/json/#serializing-json-using-code-generation-libraries

The current version of json_serializable does not use Mixins

https://pub.dartlang.org/documentation/json_serializable/latest/

**Comment by chalin** [comment] 2018-10-25 13:49
Thanks for the issue. This is a duplicate of #1255, which has been fixed by #1531.

cc @kevmoo @sfshaza2

**Comment by Twinber** [comment] 2018-10-25 17:07
Ok, but only in dash branch

**Comment by chalin** [comment] 2018-10-25 17:17
Ok, I'll make this change on master too.

**Comment by chalin** [comment] 2018-10-25 17:19
Cf. @kevmoo's comment https://github.com/flutter/website/issues/1255#issuecomment-433076862

**Comment by sfshaza2** [comment] 2018-10-29 20:17
@chalin, can this be closed?

**Comment by chalin** [comment] 2018-10-30 18:51
Yes, it was closed by #1554.

**Closed by chalin** 2018-10-30 18:51 UTC
