### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by yetiyoga123** [flutter/website#6699] opened 2022-01-20 07:22 UTC
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

lib/main.dart:24:18: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
          child: RandomWords(),
                 ^^^^^^^^^^^

### Expected fix

Removed const

**Comment by danagbemava-nc** [comment] 2022-01-20 09:22
Duplicate of #6642

**Closed by danagbemava-nc** 2022-01-20 09:22 UTC
