### ISSUE TITLE
'Adding a splash screen to your mobile app' page issue

### ISSUE THREAD

**Issue by AdrianSima** [flutter/website#5451] opened 2021-03-10 14:49 UTC
Page URL: https://flutter.dev/docs/development/ui/advanced/splash-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/splash-screen.md

Description of issue: The "Sample Code" link at the bottom of the page is a broken url: https://github.com/flutter/flutter/tree/master/dev/integration_tests/android_splash_screens

**Comment by sfshaza2** [comment] 2021-03-10 20:58
Duplicate of https://github.com/flutter/website/issues/5431
Closing

**Closed by sfshaza2** 2021-03-10 20:58 UTC
Labels: e1-hours, p2-medium
