### ISSUE TITLE
The Install-Flutter page looks buggy.

### ISSUE THREAD

**Issue by TangHuaiZhe** [flutter/website#4477] opened 2020-08-13 05:36 UTC
[Install Flutter](https://flutter.dev/get-started/) looks no good.
Tried both in Chrome and Safari.

![image](https://user-images.githubusercontent.com/7965577/90097668-10b7b180-dd69-11ea-8944-273fe6448e3f.png)

**Comment by JuYeong0413** [comment] 2020-08-13 16:07
Seems similar to #4301

**Comment by sfshaza2** [comment] 2020-08-13 16:45
Yes, it sure does, @JuYeong0413!  @TangHuaiZhe, can you give us more info, as we don't see that here. You mention Chrome and Safari, so you're on a Mac? What OS? What locale? If you could provide the output from `flutter doctor`, that would help.

**Comment by TangHuaiZhe** [comment] 2020-08-14 06:05
Hi, 
Today I tried to open this page again. I only repeated the problem once, and then everything was ok.
I feel this question has something to do with the Internet (my location is in Shanghai, China).
I find that this problem occurrs when the Flutter icon in the top left corner of the page does not appear successfully.

![image](https://user-images.githubusercontent.com/7965577/90218664-f946fa00-de36-11ea-8e54-bb9ce9b85f9b.png)




My operating system is MacOS 10.15.6 (19G73)

This is the result of the Doctor with flutter:

```
Doctor Summary (to see all details, Run Flutter Doctor - V):
[✓ Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, Locale EN-CN)
Android Toolchain-Develop for Android Devices (Android SDK Version 29.0.3) [✓.]
[!] Xcode-develop for iOS and macOS
✗ Xcode installation is incomplete; A full installation is necessary for iOS development.
Download at: https://developer.apple.com/xcode/download/
Or install Xcode via the App Store.
Once installed, run:
Sudo xcode - select - switch/Applications/xcode. The app/Contents/Developer
Sudo xcodebuild - runFirstLaunch
Android Studio (Version 4.0) [✓]
[!] IntelliJ IDEA Community Edition (Version 2019.3.3)
✗ Flutter plugin not installed; This adds Flutter specific functionality.
✗ Dart plugin not installed; This adds Dart specific functionality.
[!] VS Code (version 1.47.3)
✗ Flutter extension not installed; Install the from
https://marketplace.visualstudio.com/items? ItemName = Dart - Code. Flutter
[!] Connected device
! No devices available

! Doctor found issues in 5 categories.
```

**Comment by sfshaza2** [comment] 2020-08-14 06:45
@domesticmouse @theacodes @johnpryan: We've had a couple reports of folks that our website sometimes doesn't render correctly. This report is from a user in Shanghai, and I suspect that the other report (['Flutter SDK releases' page issue #4301](https://github.com/flutter/website/issues/4301)) is also from another locale, though the person who filed the issue hasn't confirmed that.

Is there anything we can do about this? Any reason to suspect why images might not be loading properly?

@TangHuaiZhe, thanks for the additional info you provided. Unfortunately, at the moment, we don't have website infrastructure support. It might be that the best we can do for now is to gather data and try to isolate the problem.

**Comment by domesticmouse** [comment] 2020-08-14 07:41
The missing Flutter logo makes me wonder if some part of the css is failing to load. Any errors showing up in the console logs?

**Comment by TangHuaiZhe** [comment] 2020-08-14 08:42
@domesticmouse  I will submit the console log under this issue when I run into this problem again.

**Comment by TangHuaiZhe** [comment] 2020-08-17 05:15
Update console log:
![image](https://user-images.githubusercontent.com/7965577/90359452-91d5b800-e08b-11ea-8304-63e4d0ae4c48.png)

**Comment by TangHuaiZhe** [comment] 2020-08-17 05:31
In addition, it seems that `flutter.dev` can no longer be accessed from China.
Perhaps because the [Great_Firewall.](https://en.wikipedia.org/wiki/Great_Firewall)

![image](https://user-images.githubusercontent.com/7965577/90360191-97340200-e08d-11ea-9d49-7234517a6b23.png)



If I configure the VPN, then I can visit it normally.
![image](https://user-images.githubusercontent.com/7965577/90360260-db270700-e08d-11ea-8c5c-04b2cbb8d758.png)

**Comment by domesticmouse** [comment] 2020-08-17 06:15
Have you tried https://flutter.cn/ ?

**Comment by TangHuaiZhe** [comment] 2020-08-17 06:35
@domesticmouse https://flutter.cn/ is accessible.

**Comment by sfshaza2** [comment] 2020-09-10 07:03
Yet another report:  https://github.com/flutter/website/issues/4589

**Comment by RedBrogdon** [comment] 2020-09-11 23:47
Judging by the upside down names, this looks like an issue with the Material icons. Either that font isn't getting loaded correctly or something else is causing it to fail to render properly. @karthickramanathan95 and @TangHuaiZhe, do you mind checking the network inspector in your browser and doing a full reload of the page to see if any files have failed to load (404, 500, timeout, etc.)?

**Comment by RedBrogdon** [comment] 2020-09-11 23:48
🤦 

Actually, I can see the font failing to load in the screenshot @TangHuaiZhe provided above (thanks for posting it!). That's got to be the root cause, although I have no idea why it wouldn't be loading.

**Comment by karthickramanathan95** [comment] 2020-09-14 14:10
The page is loading correctly now and I don't see any files failed to load. All files are 200 only. I don't know what fixes the issue

**Comment by karthickramanathan95** [comment] 2020-09-26 17:18
It is again happening sometimes,

![image](https://user-images.githubusercontent.com/30870272/94346337-a1acc880-0049-11eb-882d-f5d9ef52d1f6.png)

![image](https://user-images.githubusercontent.com/30870272/94346456-6232ac00-004a-11eb-8636-107e2a7e581a.png)

CSS ERR - connection timed out

Multiple times happening, sometimes on [material.io](material.io) site also.

Flutter doctor report -
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by sfshaza2** [comment] 2020-09-28 23:21
Thanks for your feedback, Karthick!

@Andrew Brogdon <redbrogdon@google.com>, do you think the Material team
might have a clue?

**Comment by RedBrogdon** [comment] 2020-09-29 00:24
Wouldn't hurt to ask. @willlarche, do you know who to talk to about an issue downloading the Material icons font?

**Comment by willlarche** [comment] 2020-09-29 02:11
Yes. I'll email.

**Comment by MiraMarshall** [comment] 2022-08-11 14:56
Closing, this issue looks like it has been addressed.

**Closed by MiraMarshall** 2022-08-11 14:56 UTC
Labels: needs-info, p1-high, e2-days
