### ISSUE TITLE
[PAGE ISSUE]: 'Introduction to widgets'

### ISSUE THREAD

**Issue by UnoJS** [flutter/website#7017] opened 2022-04-13 12:01 UTC
### Page URL

https://docs.flutter.dev/development/ui/widgets-intro/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets-intro.md

### Describe the problem

Hello world example
	textDirection: TextDirection.rtl 
this code in execution window does not reverse the whiole string but only last sign: 
	!Hello, world

### Expected fix

!dlrow ,olleH

**Comment by danagbemava-nc** [comment] 2022-04-13 12:52
Hi @UnoJS, you might be misunderstanding what the `TextDirection` property is meant to do. See https://api.flutter.dev/flutter/dart-ui/TextDirection.html for more information. 

Closing as this is working as designed and intended.  

Thank you

**Closed by danagbemava-nc** 2022-04-13 12:52 UTC
Labels: in triage
