### ISSUE TITLE
Issue from website page JSON and serialization

### ISSUE THREAD

**Issue by SangSuantak** [flutter/website#1377] opened 2018-10-03 11:44 UTC
From URL: https://flutter.io/json/

In the documentation's `user.dart` file, including serializer mixin (` extends Object with _$UserSerializerMixin`) gives error in the latest version.

**`Joke.dart`**

```
import 'package:json_annotation/json_annotation.dart';

part 'Joke.g.dart';

@JsonSerializable()
class Joke extends Object with _$JokeSerializerMixin {
  Joke(this.id, this.value);

  @JsonKey(name: 'id')
  final int id;

  @JsonKey(name: 'joke')
  final String value;

  factory Joke.fromJson(Map<String, dynamic> json) =>
      _$JokeFromJson(json);
}
```
After running `flutter packages pub run build_runner build`, i get the following code in **`Joke.g.dart`**:

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Joke.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Joke _$JokeFromJson(Map<String, dynamic> json) {
  return Joke(json['id'] as int, json['joke'] as String);
}

Map<String, dynamic> _$JokeToJson(Joke instance) =>
    <String, dynamic>{'id': instance.id, 'joke': instance.value};
```

**`Error`**:
```
Classes can only mixin other classes.
Undefined class '_$JokeSerializerMixin'.
```

Moreover, the example code [here][1] doesn't have the serializer mixin code.

[1]: https://github.com/dart-lang/json_serializable/blob/master/example/lib/example.dart

**Comment by kevmoo** [comment] 2018-10-13 22:51
Duplicate of #1255

**Closed by kevmoo** 2018-10-13 22:51 UTC
