### ISSUE TITLE
[PAGE ISSUE]: 'Obfuscating Dart code'

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/website#8105] opened 2023-01-12 21:18 UTC
### Page URL

https://docs.flutter.dev/deployment/obfuscate/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/obfuscate.md

### Describe the problem

This document claims that obfuscation is not supported on windows/linux, but it is in-fact supported.

i.e. `flutter build windows --obfuscate --split-debug-info=info` should provide an application where all dart identifiers have been scrambled.

**Comment by parlough** [comment] 2023-01-12 21:28
Duplicate of https://github.com/flutter/website/issues/4154

I’ll make sure we don’t let it slip by this time.

**Closed by parlough** 2023-01-12 21:28 UTC
