### ISSUE TITLE
Please add dark mode for docs

### ISSUE THREAD

**Issue by pakke86** [flutter/website#5933] opened 2021-06-16 19:15 UTC
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue: Want dark mode on docs.

**Comment by MrBirb** [comment] 2021-08-14 11:03
Duplicate of #3632

**Comment by TahaTesser** [comment] 2021-09-07 07:48
Closing as duplicate of https://github.com/flutter/website/issues/3632

Feel free to tag me if you want find such duplicates @MrBirb, thanks

**Closed by TahaTesser** 2021-09-07 07:48 UTC
Labels: infrastructure, p3-low, e2-days
