### ISSUE TITLE
misprint : https://codelabs.developers.google.com/codelabs/flutter-cupertino#5

### ISSUE THREAD

**Issue by JarvisHo** [flutter/website#6074] opened 2021-07-27 06:10 UTC
In lib/product_list_tab.dart, first section, `builder: (context, child, model) {` should be `builder: (context, model, child) {`

**Comment by maheshmnj** [comment] 2021-07-27 11:10
@JarvisHo, Thanks for filing the issue, This is a valid issue as per the [consumer docs](https://pub.dev/documentation/provider/latest/provider/Consumer/builder.html).

**Comment by sakshiisaxena** [comment] 2021-07-29 18:42
Is this issue up for grab? @JarvisHo

**Comment by maheshmnj** [comment] 2021-07-30 04:17
Heres the repo to contribute: https://github.com/flutter/codelabs/tree/master/cupertino_store

**Comment by micpap25** [comment] 2021-08-07 13:53
I'd like to contribute, but I ran a VSCode search through that repository and I cannot find the code `(context, child, model)` at all. Does anyone know where these pages are?

**Comment by JarvisHo** [comment] 2021-08-07 18:08
![image](https://user-images.githubusercontent.com/7737124/128609956-e9a7b5f6-ad53-4b1a-ab5b-814362906253.jpeg)

This picture might help

**Comment by maheshmnj** [comment] 2021-08-08 03:33
This issue is a duplicate of a closed issue https://github.com/flutter/website/issues/3475, But I see the codelab is still not updated and the [source code](https://github.com/flutter/codelabs/blob/master/cupertino_store/step_01/lib/product_list_tab.dart) looks correct. 

cc: @domesticmouse

**Comment by domesticmouse** [comment] 2021-08-08 09:58
Fix inbound.

**Closed** 2021-10-06 10:29 UTC
Labels: p3-low, e0-minutes, codelab
