### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter iOS apps on macOS' - instructions do not mention adding `flutter` to the `PATH`

### ISSUE THREAD

**Issue by DetachHead** [flutter/website#10043] opened 2024-01-14 02:28 UTC
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/mobile-ios.md

### Describe the problem

the install instructions seem to no longer mention adding flutter to the PATH

### Expected fix

add instructions to the ["Install the Flutter SDK" section](https://docs.flutter.dev/get-started/install/macos/mobile-ios?tab=download#install-the-flutter-sdk)

### Additional context

last time i installed flutter, i recall this being mentioned in the instructions, so maybe the section was moved or deleted?

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment] 2024-01-16 10:13
Closing as a duplicate of https://github.com/flutter/website/issues/9351. Please follow up on it for updates.

**Closed by huycozy** 2024-01-16 10:13 UTC
Labels: st.triage.triage-team, from.page-issue
