### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by SethThoburn** [flutter/website#2774] opened 2019-06-20 01:18 UTC
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Description of issue:
When copy pasting the example code, there is the error "Unexpected text 'await'."

**Comment by sfshaza2** [comment] 2019-06-20 01:44
@SethThoburn, which IDE or editor? To be clear, you saw this error when you pasted the final example into a new file called lib/db_test.dart ?

I was not able to replicate this error. The `await` keyword is part of the Dart language and, while this example pulls  in the dart:async package with `import dart:async;`, it shouldn’t even be required. The error you report suggests that there is a syntax error in an example.

Could you be more specific about exactly which text you copied? That page has several pieces of code that can be copied to the clipboard.

**Comment by SethThoburn** [comment] 2019-06-20 03:13
Putting just this code in a file:
```
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'dart:async';

final Future<Database> database = openDatabase(
  // Set the path to the database. Note: Using the `join` function from the
  // `path` package is best practice to ensure the path is correctly
  // constructed for each platform.
  join(await getDatabasesPath(), 'doggie_database.db'),
);
```

I am using vscode with the Dart Code extension version 3.1.0. It points out two errors:
 - `await`: `Unexpected text 'await'.`
 - `getDatabasesPath()`: `The argument type 'Future<String>' can't be assigned to the parameter type 'String'.`

**Comment by brianegan** [comment] 2019-06-25 14:29
Heya @SethThoburn -- I've double-checked, and copying and pasting the complete example into a new file works as expected.

In order to use the `await` keyword, the code must sit inside an `async` function. In the complete example, the `main` function is an `async` function, so the `await` keyword works just fine in that context!

Are you copying and pasting this code into a non-async function by chance?

**Comment by sfshaza2** [comment] 2019-07-09 00:50
Cannot reproduce. Closing.

**Closed by sfshaza2** 2019-07-09 00:50 UTC
Labels: can't reproduce, cookbook, waitingForCustomerResponse

**Comment by hammad-tariq** [comment] 2019-09-18 07:19
@SethThoburn 
This issue occurs if write above code outside main method.
If you write your code like below it will work as expected.

`
void main() async {
  final database = openDatabase(
    // Set the path to the database. Note: Using the `join` function from the
    // `path` package is best practice to ensure the path is correctly
    // constructed for each platform.
    join(await getDatabasesPath(), 'doggie_database.db'),
// When the database is first created, create a table to store dogs.
    onCreate: (db, version) {
      return db.execute(
        "CREATE TABLE dogs(id INTEGER PRIMARY KEY, name TEXT, age INTEGER)",
      );
    },
// Set the version. This executes the onCreate function and provides a
// path to perform database upgrades and downgrades.
    version: 1,
  );
}`

**Comment by vzool** [comment] 2020-06-29 04:23
> Putting just this code in a file:
> 
> ```
> import 'package:path/path.dart';
> import 'package:sqflite/sqflite.dart';
> import 'dart:async';
> 
> final Future<Database> database = openDatabase(
>   // Set the path to the database. Note: Using the `join` function from the
>   // `path` package is best practice to ensure the path is correctly
>   // constructed for each platform.
>   join(await getDatabasesPath(), 'doggie_database.db'),
> );
> ```
> 
> I am using vscode with the Dart Code extension version 3.1.0. It points out two errors:
> 
> * `await`: `Unexpected text 'await'.`
> * `getDatabasesPath()`: `The argument type 'Future<String>' can't be assigned to the parameter type 'String'.`

Hi, if you like to make a unified `database` instance for the whole application, I suggest this way:

```dart

const version = 1;
const fileName = 'project.db';

Future<Database> database() async {

  // Open the database and store the reference.
  return  openDatabase(
    // Set the path to the database. Note: Using the `join` function from the
    // `path` package is best practice to ensure the path is correctly
    // constructed for each platform.
    // Set the path to the database.
    join(await getDatabasesPath(), fileName),

    // When the database is first created, create a table to store dogs.
    onCreate: (db, version) {
      // Run the CREATE TABLE statement on the database.
      // ..
    },
    // Set the version. This executes the onCreate function and provides a
    // path to perform database upgrades and downgrades.
    version: version,
  );
}
```

Hope this will be helpful to you. ^_^
