### ISSUE TITLE
Fix issue where Download link shows incorrect text on 'Windows install' page

### ISSUE THREAD

**Issue by HamzaAhmedShad** [flutter/website#3982] opened 2020-04-22 05:19 UTC
Page URL: https://docs.flutter.dev/get-started/install/windows
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:
![flutter failed](https://user-images.githubusercontent.com/35128191/79943594-0ce6e300-848b-11ea-9bc9-7ab9fb7ab6c7.png)

**Comment by sfshaza2** [comment] 2020-04-23 02:32
@tvolkert, we get a trickle of reports like this, with no idea why. For example:

https://github.com/flutter/website/issues/1909
https://github.com/flutter/website/issues/2595

Any ideas?

**Comment by tvolkert** [comment] 2020-05-19 18:29
@iiVOXODii if you're using Chrome, I'd be interested in seeing the Chrome Tools network tab when you see this issue.

@godofredoc is this because the GCP bucket fails to serve traffic occasionally?  Do we have stats on that?

**Comment by godofredoc** [comment] 2023-05-23 01:27
For https://github.com/flutter/website/issues/1909 and
https://github.com/flutter/website/issues/2595: 

Depending on the download location it could be related to how the client browser processes slow downloads. The flutter bundles are hosted in a Google Cloud Storage that are only replicated across the US.

@tvolkert unless the issue is happening consistently for multiple users it is unlikely that GCS is failing to serve traffic and it is most likely a client side problem.


@HamzaAhmedShad it would be great if you can share a screenshot of the network and console tabs of the devtools to help us triage the problem.

**Comment by sfshaza2** [comment] 2023-05-24 19:42
I'm closing this as not reproducible. We've had no reports in the last 3 years.

**Closed by sfshaza2** 2023-05-24 19:42 UTC
Labels: bug, getting started, infrastructure, p1-high, e1-hours, a: install, devp:Win, ltw-triage, from:page-issue
