### ISSUE TITLE
Disproportional Images in the main page

### ISSUE THREAD

**Issue by rumaan** [flutter/website#1935] opened 2018-12-07 07:07 UTC
In the section, "**Who's using Flutter?**" the images aren't in proper proportions. 

![screenshot 2018-12-07 at 12 30 32 pm](https://user-images.githubusercontent.com/18492868/49632611-5791c780-fa1c-11e8-8a9f-f3a7c359c3f1.png)

**Comment by chalin** [comment] 2018-12-07 16:54
Hi! Thanks for the issue. It is, I believe, a duplicate of #1750. If you aren't experiencing this under Firefox, please reopen this issue and provide browser information.

**Closed by chalin** 2018-12-07 16:54 UTC
Labels: duplicate
