### ISSUE TITLE
support for dark mode 

### ISSUE THREAD

**Issue by samithe7** [flutter/website#8404] opened 2023-03-17 22:02 UTC
### Page URL

https://flutter.dev/

### Describe the problem

we almost all developer  use dark  mode  . when  i go flutter website it is  too white  .

**Comment by parlough** [comment] 2023-03-17 22:12
Thanks for opening an issue. This work is planned in https://github.com/flutter/website/issues/3632, but some other work is set to be complete first. Sorry about the delay.

Duplicate of https://github.com/flutter/website/issues/3632

**Closed by parlough** 2023-03-17 22:12 UTC
