### ISSUE TITLE
[PAGE ISSUE]: 'Documentation missing details on setting flutter path'

### ISSUE THREAD

**Issue by dkarthicks27** [flutter/website#10018] opened 2024-01-09 19:07 UTC
### Page URL

https://docs.flutter.dev/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/index.md

### Describe the problem

The Documentation on installation, doesn't provide details on to set flutter path. This cause flutter not found. Please fix the documentation for mac.
<img width="981" alt="Screenshot 2024-01-10 at 12 35 36 AM" src="https://github.com/flutter/website/assets/59522740/9c222b09-7244-4766-8e3f-f01de9ffb2ae">
<img width="922" alt="Screenshot 2024-01-10 at 12 36 02 AM" src="https://github.com/flutter/website/assets/59522740/6c99758d-120c-4799-b75e-c97b41ed27aa">

### Expected fix

Fix the documentation by adding details on how to set the flutter path to our environment variables.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment] 2024-01-10 11:28
Closing as a duplicate of https://github.com/flutter/website/issues/9351.

**Closed by huycozy** 2024-01-10 11:28 UTC
Labels: st.triage.triage-team, from.page-issue
