### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by KanTakahiro** [flutter/website#6704] opened 2022-01-21 02:34 UTC
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

In "Step 3: Add a Stateful widget", after I edited the code follow the tutorial and reload the app, it gave me a error:
```
lib/main.dart:23:18: Error: Cannot invoke a non-'const' constructor where a
const expression is expected.
Try using a constructor or factory that is 'const'.
          child: RandomWords(),
                 ^^^^^^^^^^^
```
I am not very familiar with Flutter but I think the word "const" in the line `body: const Center(` caused the error. I removed the word "const" and the app built successfully. Is this a mistake in the tutorial?

### Expected fix

App built or run without any error.

### Additional context

This is my whole `main.dart` code.
```
// Copyright 2018 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: RandomWords(),
        ),
      ),
    );
  }
}

class RandomWords extends StatefulWidget {
  @override
  _RandomWordsState createState() => _RandomWordsState();
}

class _RandomWordsState extends State<RandomWords> {
  @override
  Widget build(BuildContext context) {
    final wordPair = WordPair.random();
    return Text(wordPair.asPascalCase);
  }
}
```

**Comment by KanTakahiro** [comment] 2022-01-21 04:10
In Part 4, there is a same error occured. I have to remove "const" from `Widget build`. This is my code:
```
// Copyright 2018 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(    \\I have to remove this "const"
      title: 'Startup Name Generator',
      home: RandomWords(),
    );
  }
}

class RandomWords extends StatefulWidget {
  @override
  _RandomWordsState createState() => _RandomWordsState();
}

class _RandomWordsState extends State<RandomWords> {
  final _suggestions = <WordPair>[];
  final _biggerFont = const TextStyle(fontSize: 18.0);

  Widget _buildSuggestions() {
    return ListView.builder(
        padding: const EdgeInsets.all(16.0),
        itemBuilder: (context, i) {
          if (i.isOdd) return const Divider();

          final index = i ~/ 2;
          if (index >= _suggestions.length) {
            _suggestions.addAll(generateWordPairs().take(10));
          }
          return _buildRow(_suggestions[index]);
        });
  }

  Widget _buildRow(WordPair pair) {
    return ListTile(
      title: Text(
        pair.asPascalCase,
        style: _biggerFont,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Startup Name Generator'),
      ),
      body: _buildSuggestions(),
    );
  }
}
```

**Comment by danagbemava-nc** [comment] 2022-01-21 11:20
Duplicate of #6642

Hi @KanTakahiro, there's a pr in progress in https://github.com/flutter/website/pull/6707 which should address this issue. 

Closing as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-01-21 11:20 UTC
Labels: in triage
