### ISSUE TITLE
[PAGE ISSUE]: 'State management'. Page is blank.

### ISSUE THREAD

**Issue by ansh-les** [flutter/website#7175] opened 2022-05-22 16:36 UTC
### Page URL

https://docs.flutter.dev/development/data-and-backend/state-mgmt/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/state-mgmt/index.md

### Describe the problem

Page is empty.

### Additional context

![image](https://user-images.githubusercontent.com/57872180/169706006-c9723415-a78c-4477-b559-64c4fc8740c7.png)

**Comment by danagbemava-nc** [comment] 2022-05-23 13:08
Closing this as a duplicate of https://github.com/flutter/website/issues/6758

**Closed by danagbemava-nc** 2022-05-23 13:08 UTC
Labels: in triage
