### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by rjkilpatrick** [flutter/website#6636] opened 2022-01-06 20:12 UTC
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

> The `main()` method uses arrow (`=>`) notation. Use arrow notation for one-line functions or methods.

However, the `main` method does not use arrow notation.
https://github.com/flutter/website/blob/b8fc927a2e35829efc19b941d0a1ac2517b185f6/src/get-started/codelab.md?plain=1#L124-L153

### Expected fix

Either re-writing the main function using arrow notation or removing this point from the list of observations.

**Comment by danagbemava-nc** [comment] 2022-01-07 08:11
Duplicate of #6608

**Closed by danagbemava-nc** 2022-01-07 08:11 UTC
Labels: in triage
