### ISSUE TITLE
Dark mode for website 🌙

### ISSUE THREAD

**Issue by fadhilsaheer** [flutter/website#6146] opened 2021-08-14 09:56 UTC
### Page URL

https://flutter.dev

### Describe the problem

We need dark mode for https://flutter.dev/
> The only reason why I hate flutter is because it don't have dark mode for docs 🥵

Reading docs is the base of building next billion dollar todo app (or any app in general) As developers, we know light attracts bugs and our eye takes more strain to read the content inside the page which will lead to many serious risks 😕

### Expected fix

Dark Mode !!!

**Comment by MrBirb** [comment] 2021-08-14 11:03
Duplicate of #3632

**Comment by TahaTesser** [comment] 2021-08-16 14:54
Closing as duplicate of https://github.com/flutter/website/issues/6146

**Closed by TahaTesser** 2021-08-16 14:54 UTC
Labels: in triage
