### ISSUE TITLE
Add dark mode for the website

### ISSUE THREAD

**Issue by nnhhiilliisstt** [flutter/website#4095] opened 2020-05-15 05:23 UTC

**Comment by apravint** [comment] 2020-05-16 06:27
#3632 is already open for this.. :)

**Comment by apravint** [comment] 2020-05-16 06:28
Duplicate of #3632

**Comment by nnhhiilliisstt** [comment] 2020-05-16 06:43
#3632 is about adding dark mode to the flutter documentation, this one is about adding dark mode to the website itself

**Comment by apravint** [comment] 2020-05-16 06:46
#2952 for the dark mode to the website. please take a look.

**Comment by sfshaza2** [comment] 2020-05-17 18:49
https://github.com/flutter/website/issues/3632 is most definitely asking for dark mode on the flutter.dev website, so this is a dupe. Closing.

(To file a request for dark mode on the api.flutter.dev docs, file an issue on the flutter/flutter repo.)

**Closed by sfshaza2** 2020-05-17 18:49 UTC
