### ISSUE TITLE
[PAGE ISSUE]: 'Integrate a Flutter module into your Android project'

### ISSUE THREAD

**Issue by linslouis** [flutter/website#7295] opened 2022-06-22 07:14 UTC
### Page URL

https://docs.flutter.dev/development/add-to-app/android/project-setup/

### Page source

https://github.com/flutter/website/tree/main/src/development/add-to-app/android/project-setup.md

### Describe the problem

Inside File > New > New Module , there is no option to add flutter module. Even the window is totally different than the current android studio Chipmunk 2021.2.1 Patch 1.

### Expected fix

Update documentation

**Comment by danagbemava-nc** [comment] 2022-06-22 09:35
Closing this as a duplicate of https://github.com/flutter/website/issues/7223

**Closed by danagbemava-nc** 2022-06-22 09:35 UTC
Labels: in triage
