### ISSUE TITLE
'Animate a page route transition' page issue

### ISSUE THREAD

**Issue by vstyler96** [flutter/website#3573] opened 2020-01-22 18:51 UTC
Page URL: https://flutter.dev/docs/cookbook/animation/page-route-animation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/animation/page-route-animation.md

Description of issue:
Dart SDK is not working for preview

**Comment by legalcodes** [comment] 2020-01-22 21:54
Thanks @vstyler96 for raising this! I wasn't able to identify the page issue -- the embedded DartPad example seems to be running fine (in Chrome and Firefox). Can you be more specific about the steps to reproduce the problem you observed?

**Comment by sfshaza2** [comment] 2020-01-23 03:24
I'm wondering what's up. We got this bug yesterday:  https://github.com/flutter/website/issues/3567

But, so far, can't reproduce it without more info.

**Comment by sfshaza2** [comment] 2020-03-25 01:03
Closing.

**Closed by sfshaza2** 2020-03-25 01:03 UTC
Labels: cookbook, needs-info, waitingForCustomerResponse
