### ISSUE TITLE
[PAGE ISSUE]: the source has a problem

### ISSUE THREAD

**Issue by joonseolee** [flutter/website#6789] opened 2022-02-07 00:18 UTC
## Page URL

https://flutter-ko.dev/docs/cookbook/forms/retrieve-input

## Page source

https://github.com/flutter/website/blob/main/src/cookbook/forms/retrieve-input.md

## Describe the problem 

I tried to do cookbook subjects.
but I wrote this below code it has a wrong word.  
you can see the five line code including return word.
`onPreseed` equals `void Function();` so it cannot return widget class.
am I wrong? 
thank you for reading this issue.

```dart
      floatingActionButton: FloatingActionButton(
        // When the user presses the button, show an alert dialog containing
        // the text that the user has entered into the text field.
        onPressed: () {
          return showDialog(
            context: context,
            builder: (context) {
              return AlertDialog(
                // Retrieve the text the that user has entered by using the
                // TextEditingController.
                content: Text(myController.text),
              );
            },
          );
        },
        tooltip: 'Show me the value!',
        child: Icon(Icons.text_fields),
      ),
```

**Comment by danagbemava-nc** [comment] 2022-02-08 10:13
Hi @joonseolee, you are right that the `onPressed` doesn't need the `return`. 

However, the linked page is community-maintained and since we have no way of contacting the maintainers, we cannot get them to fix the issue. 

Closing as the issue is on a community-maintained site.

Thank you

**Closed by danagbemava-nc** 2022-02-08 10:13 UTC
Labels: in triage
