### ISSUE TITLE
Need to explain how to add OEM UI views and textures to Flutter apps

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2063] opened 2018-12-17 14:57 UTC
@eseidelGoogle commented on [Thu Mar 22 2018](https://github.com/flutter/flutter/issues/15832)

https://flutter.io/platform-channels/ doesn't mention UI.  It could point to:
https://github.com/flutter/flutter/tree/master/examples/platform_view
https://github.com/flutter/flutter/tree/master/examples/flutter_view
or in the case of foreign Textures (like for AR, GL, etc.):
https://github.com/flutter/plugins/tree/master/packages/video_player
https://github.com/flutter/plugins/tree/master/packages/camera

Maybe some of this will happen as part of other add-to-app work @mravn-google and co are looking at.

---

@zoechi commented on [Tue Dec 04 2018](https://github.com/flutter/flutter/issues/15832#issuecomment-444105838)

Is this a dup of #14927 ?

**Comment by zoechi** [comment] 2018-12-17 14:58
I guess this is a dup of #2064 (previously flutter/flutter#14927 as mentioned above)

**Comment by sfshaza2** [comment] 2019-06-10 18:14
Closing as dupe of https://github.com/flutter/website/issues/2064

**Closed by sfshaza2** 2019-06-10 18:14 UTC
