### ISSUE TITLE
[PAGE ISSUE]: 'Layouts in Flutter'

### ISSUE THREAD

**Issue by hanskokx** [flutter/website#6690] opened 2022-01-18 17:09 UTC
### Page URL

https://docs.flutter.dev/development/ui/layout#gridview

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/layout/index.md

### Describe the problem

The GridView.count example has a link to [grid_list_demo.dart](https://github.com/flutter/flutter/tree/main/dev/integration_tests/flutter_gallery/lib/demo/material/grid_list_demo.dart) which is broken.

### Expected fix

The link should navigate to source code for the example rather than 404.

**Comment by danagbemava-nc** [comment] 2022-01-19 11:31
Duplicate of #6463

**Closed by danagbemava-nc** 2022-01-19 11:31 UTC
Labels: in triage
