### ISSUE TITLE
EventChannel missing documentation article

### ISSUE THREAD

**Issue by hawkkiller** [flutter/website#8772] opened 2023-05-28 14:22 UTC
### What information is missing?

The topic on event channels and communication using event channels with platform.

### How would you like us to fix this problem?

Create an article :)

**Comment by danagbemava-nc** [comment] 2023-05-29 12:48
Closing this as a duplicate of https://github.com/flutter/website/issues/8098.

**Closed by danagbemava-nc** 2023-05-29 12:48 UTC
Labels: in triage
