### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by jetchirag** [flutter/website#6623] opened 2022-01-02 14:33 UTC
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

In observation it's mentioned:

> The main() method uses arrow (=>) notation. Use arrow notation for one-line functions or methods.

But the main function does not use arrow notations:

```
void main() {
  runApp(const MyApp());
}
```

### Expected fix

could be:

`void main() =>  runApp(const MyApp());`

### Additional context

New to this language, let me know if I'm wrong.

**Comment by danagbemava-nc** [comment] 2022-01-03 10:16
Duplicate of #6608

**Closed by danagbemava-nc** 2022-01-03 10:16 UTC
Labels: in triage
