### ISSUE TITLE
executor failed running [/bin/sh -c flutter doctor]: exit code: 127 Service 'site' failed to build : Build failed

### ISSUE THREAD

**Issue by kabagouda** [flutter/website#6677] opened 2022-01-13 09:47 UTC
### Describe the problem

I am building this website and when I run `make setup`, everything is fine until :

> [dev 15/17] RUN flutter doctor 

![Capture](https://user-images.githubusercontent.com/64534846/149305979-c149681d-1681-40b8-9f9b-d685fd5fec79.PNG)

 
PS: I have installed all the prerequisites and everything works fine. I tried several times but I'm still blocked

**Comment by InMatrix** [comment] 2022-02-01 23:31
I ran into a similar issue today. Here's the error log:
```
$ make setup             
make clean
rm -rf _site .jekyll* src/.jekyll* *.log tmp example.g .dart_tool
docker-compose build site
WARN[0000] The "DISABLE_TESTS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FIREBASE_ALIAS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FIREBASE_TOKEN" variable is not set. Defaulting to a blank string. 
[+] Building 9.9s (19/21)                                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 32B                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 34B                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ruby:3.0-buster                                                                                                      0.6s
 => [dev  1/17] FROM docker.io/library/ruby:3.0-buster@sha256:73271712d33818aa324b0766b2913b3661c01c6964dd5b629ef656fae076125a                                          0.0s
 => [internal] load build context                                                                                                                                       1.7s
 => => transferring context: 2.41MB                                                                                                                                     1.6s
 => CACHED [dev  2/17] RUN curl -sL https://deb.nodesource.com/setup_17.x -o node_setup.sh &&       bash node_setup.sh 1> /dev/null                                     0.0s
 => CACHED [dev  3/17] RUN apt-get update && apt-get install -yq --no-install-recommends       build-essential       vim       git       diffutils       xdg-user-dirs  0.0s
 => CACHED [dev  4/17] WORKDIR /app                                                                                                                                     0.0s
 => CACHED [dev  5/17] RUN gem install bundler                                                                                                                          0.0s
 => CACHED [dev  6/17] COPY Gemfile Gemfile.lock ./                                                                                                                     0.0s
 => CACHED [dev  7/17] RUN bundle install                                                                                                                               0.0s
 => CACHED [dev  8/17] COPY package.json package-lock.json ./                                                                                                           0.0s
 => CACHED [dev  9/17] RUN npm install -g npm firebase-tools superstatic                                                                                                0.0s
 => CACHED [dev 10/17] RUN npm install                                                                                                                                  0.0s
 => CACHED [dev 11/17] RUN npm i re2                                                                                                                                    0.0s
 => [dev 12/17] COPY ./ ./                                                                                                                                              6.7s
 => [dev 13/17] RUN git submodule update --init --recursive                                                                                                             0.3s
 => [dev 14/17] RUN if test -n "" -a "" != "stable" ; then       cd flutter &&       git fetch &&       git remote set-branches origin "" &&       git fetch --depth 1  0.3s
 => ERROR [dev 15/17] RUN flutter doctor                                                                                                                                0.3s
------
 > [dev 15/17] RUN flutter doctor:
#19 0.255    Woah! You appear to be trying to run flutter as root.
#19 0.255    We strongly recommend running the flutter tool without superuser privileges.
#19 0.255   /
#19 0.255 📎
#19 0.269 /app/flutter/bin/internal/shared.sh: line 227: /app/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c flutter doctor]: exit code: 126
make: *** [setup] Error 17
```

**Comment by khanhnwin** [comment] 2022-02-01 23:54
Hi all, 
Can I have the steps that invoked that error? I just pulled from main + tried running `make setup` myself but wasn't able to replicate.

**Comment by InMatrix** [comment] 2022-02-02 00:29
@khanhnwin After restarting from a fresh fork, the error is gone. I think it's probably caused by some artifacts in my old fork. I'm not sure if OP's issue is related, but I'd encourage @kagouda to try a fresh fork as well.

**Comment by khanhnwin** [comment] 2022-02-02 15:26
Thanks @InMatrix! I'm happy to hear the fresh fork worked out. If either of y'all are able to replicate the issue again – please do report back! This would be good to have documented :)

**Comment by parlough** [comment] 2023-01-06 00:45
I'm going to close this as a lot of changes, improvements, and fixes have been made to our infrastructure setup since this issue was created and it seems no one has hit the issue since.

If anyone is still experiencing this with a fresh fork following the [instructions in the README](https://github.com/flutter/website#flutter-website), let us know and we can revisit this. Thanks!

**Closed by parlough** 2023-01-06 00:45 UTC
Labels: infrastructure, p2-medium
