### ISSUE TITLE
Fix `TypeMatcher` to `isA` in 'Mock dependencies using Mockito' page

### ISSUE THREAD

**Issue by danagbemava** [flutter/website#4120] opened 2020-05-21 22:48 UTC
Page URL: https://flutter.dev/docs/cookbook/testing/unit/mocking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description of issue:

``` TypeMatcher<T> ``` has been deprecated in favor of  ``` isA<T>```

I think this needs to be reflected in the code snippet to allow beginners to know what to do in case they run into the deprecation warning.

**Comment by sfshaza2** [comment] 2020-05-22 00:21
Actually, the problem is worse than that. This recipe relies on an earlier recipe, [Fetch Data from the internet](https://flutter.dev/docs/cookbook/networking/fetch-data). That class has been reworked to use the `Album` class, and `fetchAlbum` function. But this page assumes it's still using the `Post` class, and the `fetchPost` function. This needs to be fixed before the deprecation issue can be addressed.

**Comment by danagbemava** [comment] 2020-05-25 20:42
I just noticed that, however, I think that because this recipe defines the `Post` class and `fetchPost` method, the issue can be resolved. Although I understand that for the sake of continuity, they all have to resolved. Thanks for drawing my attention to it

**Comment by atsansone** [comment] 2023-05-30 21:01
This code has already been changed as described in https://github.com/flutter/website/pull/5492. Closing this issue.

See also: https://github.com/flutter/website/issues/3952

**Closed by atsansone** 2023-05-30 21:01 UTC
Labels: p2-medium, cookbook, e1-hours, fixed, ltw-triage, from:page-issue, testing
