### ISSUE TITLE
Step 5(Customize the sign-in Screen): Sign-In Screen for Web not showing logo in the header on Chrome

### ISSUE THREAD

**Issue by crysaro** [flutter/website#9270] opened 2023-08-19 06:46 UTC
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#4

### Describe the problem

After specifying the headerBuilder on SignInScreen basing on the instructions and debugging the app on the browser the logo in the header is not shown. The Browser is maximized when it loads. It shows up when I reduce the width of the browser.

```
 headerBuilder: (context, constraints, shrinkOffset
) {
             return Padding(
               padding: const EdgeInsets.all(20),
               child: AspectRatio(
                 aspectRatio: 1,
                 child: Image.asset('flutterfire_300x.png'),
               ),
             );
           }
```

![Screenshot from 2023-08-19 14-35-07](https://github.com/flutter/website/assets/5291882/dc0ad7a3-f6a0-477f-8007-c41f12f41f0f)
![Screenshot from 2023-08-19 14-35-54](https://github.com/flutter/website/assets/5291882/a8fee518-d131-40c9-af15-19aa90585026)

### Expected fix

The logo will be shown even though the browser is maximized.

### Additional context

Running on Ubuntu 22 LTS. The Browser is Chrome Version 115.0.5790.170 (Official Build) (64-bit)

**Comment by SakshamSahu** [comment] 2023-08-20 19:13
Hello @crysaro! Where can I locate the sign-in screens dart code file? I'll try to fix the error as I think the error might be related to how the constraints and layout are being handled in the code.

**Comment by SakshamSahu** [comment] 2023-08-21 04:35
@crysaro Where can I find this SignInScreen flutter/firebase code file where the headerBuilder is located?

**Comment by danagbemava-nc** [comment] 2023-08-21 13:11
Hi @crysaro, this seems like a bug in either flutter web or the flutterfire_ui package. 
I would advise that you file an issue on the flutterfire_ui package repo first to see if there's anything they can do on their end. 
If not, you can file an issue on the flutter repo. 

Closing as this is not a bug in the codelab since as you stated, the image shows at certain browser resolutions. The codelab doesn't do anything related to that

**Closed as not planned by danagbemava-nc** 2023-08-21 13:11 UTC
Labels: st.invalid
