### ISSUE TITLE
[PAGE ISSUE]: 'List of state management approaches'

### ISSUE THREAD

**Issue by nyck33** [flutter/website#6236] opened 2021-09-07 06:35 UTC
### Page URL

https://flutter.dev/docs/development/data-and-backend/state-mgmt/options/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/data-and-backend/state-mgmt/options.md

### Describe the problem

needs dark mode

**Comment by TahaTesser** [comment] 2021-09-07 07:48
Closing as duplicate of https://github.com/flutter/website/issues/3632

**Closed by TahaTesser** 2021-09-07 07:48 UTC
Labels: in triage
