### ISSUE TITLE
Make 'Accessing 'Support for WebAssembly (Wasm)' available via the left navigation

### ISSUE THREAD

**Issue by 911432** [flutter/website#8854] opened 2023-06-08 06:49 UTC
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/web/wasm.md

### Describe the problem

Why is this page not accessible from the left menu?

### Expected fix

Enable access from the left menu.

**Comment by darshankawar** [comment] 2023-06-08 13:06
@911432 
Do you mean accessing the option from below menu ?

<img width="245" alt="Screenshot 2023-06-08 at 6 35 15 PM" src="https://github.com/flutter/website/assets/67046386/700029aa-301b-4506-b131-b82275d07403">

If so, please see [this](https://github.com/flutter/website/issues/8473#issuecomment-1492303178) and check if it helps.

**Comment by kevmoo** [comment] 2023-06-08 17:38
Duplicate of https://github.com/flutter/website/issues/8473 – intentional

**Closed by kevmoo** 2023-06-08 17:38 UTC
Labels: p2-medium, e0-minutes, st.triage.triage-team, waiting for customer response, st.triage.ltw, from.page-issue

**Comment by 911432** [comment] 2023-06-10 12:10
@darshankawar That's right. That's what I want to say.

**Comment by 911432** [comment] 2023-06-10 12:13
@ kevmoo I wanted to change from an existing issue, but it was closed so I created a new issue.
But the issue keeps coming to an end.

**Comment by 911432** [comment] 2023-06-10 12:13
@kevmoo I wanted to change from an existing issue, but it was closed so I created a new issue.
But the issue keeps coming to an end.

**Comment by 911432** [comment] 2023-06-10 12:16
@darshankawar That's right. That's what I want to say. I didn't know it was already an issue.
