### ISSUE TITLE
'Desktop support for Flutter' page issue

### ISSUE THREAD

**Issue by tmx11** [flutter/website#4415] opened 2020-07-31 21:53 UTC
Page URL: https://flutter.dev/desktop.html
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

For linux it should add requirements cmake3 needs to be installed and set as default.

And ninja-build needs to be installed.

Error:

`flutter run
2020/07/31 17:30:22.504999 cmd_run.go:563: WARNING: XAUTHORITY environment value is not a clean path: "/run/lightdm/sroot/xauthority"
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Exception: Build process failed
`

still some further issue.

**Comment by sfshaza2** [comment] 2020-08-04 14:46
@stuartmorgan

**Comment by stuartmorgan** [comment] 2020-08-04 15:36
> For linux it should add requirements cmake3 needs to be installed and set as default.
>
> And ninja-build needs to be installed.

CMake and Ninja are both listed as requirements on that page already (as well as both being checked by `flutter doctor`) so I'm not clear on what the issue here is.

> `Exception: Build process failed`
>
> still some further issue.

You haven't included the full error, so it's impossible to tell what the problem is; without knowing that it's not at all clear that it's a documentation problem.

**Comment by sfshaza2** [comment] 2020-09-11 07:51
Closing.

**Closed by sfshaza2** 2020-09-11 07:51 UTC
Labels: e1-hours, p2-medium, waitingForCustomerResponse
