### ISSUE TITLE
Please add documentation on how to use --dart-define on flutter.dev

### ISSUE THREAD

**Issue by escamoteur** [flutter/website#5852] opened 2021-04-27 10:28 UTC
Hi,

I just spent about 10 minutes googling for how we can pass environment variables during built time and was pretty surprised that this topic isn't included under the deploy section flutter.dev

As regular questions on how to store API keys on github appear which is especially important for open source repositories where you can't include API keys or in case you use an CI server you need some way to pass where used during the time.

So please add a section in the official documentation. If I hadn't read somewhere in the past that this is possible at all I would have no clue how to search for it.

Thanks a lot for the amazing work that the flutter documentation team has already done.

Cheers
Thomas

**Comment by parlough** [comment] 2023-01-05 04:49
I'm going to close this as a duplicate of https://github.com/flutter/website/issues/4215. This still needs to be addressed.

**Closed by parlough** 2023-01-05 04:49 UTC
Labels: p2-medium, e2-days
