### ISSUE TITLE
Fix Flutter cache was unexpected error with 'Windows install' page

### ISSUE THREAD

**Issue by carlyonj** [flutter/website#2515] opened 2019-03-14 02:25 UTC
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

Unable to install on windows. Followed directions and verified many times that everything is correct. I get the below error any time I try and use the flutter command in command prompt, power shell and with various admin rights on all of them.

```
flutter
\Flutter\flutter\bin\cache was unexpected at this time.
```

**Comment by sfshaza2** [comment] 2019-06-10 18:26
Have not received other reports about this. If anyone has seen it or knows the cause, please weigh in.

**Comment by atsansone** [comment] 2023-05-19 05:18
No further information has been provided in four years and no information has been found elsewhere to provide a way to resolve this issue. Closing.

**Closed by atsansone** 2023-05-19 05:18 UTC
Labels: p1-high, e2-days, a: install, devp:Win, ltw-triage
