### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by fennelhans** [flutter/website#6773] opened 2022-02-03 15:22 UTC
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

echo.websocket.org is no longer available, according to their website. Therefore, the demo does not work as intended.

**Comment by danagbemava-nc** [comment] 2022-02-04 12:52
Duplicate of #6382

**Closed by danagbemava-nc** 2022-02-04 12:52 UTC
Labels: in triage
