### ISSUE TITLE
[PAGE ISSUE]: 'Advanced UI'

### ISSUE THREAD

**Issue by maverick110** [flutter/website#6903] opened 2022-03-11 11:15 UTC
### Page URL

https://docs.flutter.dev/development/ui/advanced/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/advanced/index.md

### Describe the problem

Nothing is there! lol

**Comment by danagbemava-nc** [comment] 2022-03-11 11:43
Duplicate of #6565

**Closed by danagbemava-nc** 2022-03-11 11:43 UTC
Labels: in triage
