### ISSUE TITLE
right-hand toc 'current highlighted' behavior is off by 1

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#2678] opened 2019-05-20 20:56 UTC
![Screen Shot 2019-05-20 at 1 41 57 PM](https://user-images.githubusercontent.com/5550175/58050752-117d7b80-7b05-11e9-8a3f-d1b3aaaf8736.png)

dart.dev/docs/codelabs#building-beautiful-uis-with-flutter

The current toc highlights the wrong hash link after click.

**Comment by sfshaza2** [comment] 2020-05-02 02:03
I can't reproduce this. Closing.

**Closed by sfshaza2** 2020-05-02 02:03 UTC
Labels: e2-days, infrastructure, p2-medium
