### ISSUE TITLE
Example on website page JSON and serialization should be updated

### ISSUE THREAD

**Issue by eturk1** [flutter/website#1290] opened 2018-09-21 09:01 UTC
Instructions at URL: https://flutter.io/json/#setting-up-json_serializable-in-a-project do not work with latest package versions.

Example on instruction page should probably be updated to use latest example here or similar: https://pub.dartlang.org/documentation/json_serializable/latest/

Packages have been substantially updated so build_runner would now create
`_$UserToJson`
instead of 
`_$UserSerializerMixin`
AND one no longer needs to extend their class with `_$UserSerializerMixin`

Note two packages are upgraded to 1.x since example was written:
```
dependencies:
  json_annotation: ^0.2.3 #is now v1.2.0

dev_dependencies:
  build_runner: ^0.9.0 #is now v0.10.2
  json_serializable: ^0.5.4` #is now v1.3.0

```

**Comment by kevmoo** [comment] 2018-10-13 22:51
Duplicate of #1255

**Closed by kevmoo** 2018-10-13 22:51 UTC
