### ISSUE TITLE
[PAGE ISSUE]: 'Obfuscating Dart code'

### ISSUE THREAD

**Issue by fryette** [flutter/website#7430] opened 2022-08-05 09:20 UTC
### Page URL

https://docs.flutter.dev/deployment/obfuscate/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/obfuscate.md

### Describe the problem

I tried to obfuscate Linux apps and seems it's working. Would be nice to update the info.

### Expected fix

Update info for linux platform

### Additional context

All steps applicable to Linux platform

**Comment by sfshaza2** [comment] 2022-08-15 17:41
Looks simple enough. Confirm and update the "Linux" field to say supported.

**Comment by parlough** [comment] 2023-01-13 01:50
Closing as a duplicate of https://github.com/flutter/website/issues/7430. Thanks for opening an issue!

**Closed by parlough** 2023-01-13 01:50 UTC
Labels: p2-medium, e0-minutes
