### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases'

### ISSUE THREAD

**Issue by ninagon666** [flutter/website#6622] opened 2022-01-01 19:54 UTC
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

It works may be not good, alaways show loading in the download list.

**Comment by ninagon666** [comment] 2022-01-01 19:56
![image](https://user-images.githubusercontent.com/80187628/147859077-9adb755a-d189-41dd-b86a-629df2ab0d3c.png)
I make sure my network with no problem.

**Comment by danagbemava-nc** [comment] 2022-01-03 10:18
Hi @ninagon666, can you check your console to see if there are any errors in there? 

I tried to load the page, and it worked just fine for me. See screenshot below

![Screenshot 2022-01-03 at 10 17 32](https://user-images.githubusercontent.com/88313112/147919688-64b134cb-e6bf-40c0-a39e-d579a7b0c7f4.png)

**Comment by ninagon666** [comment] 2022-01-03 10:35
![image](https://user-images.githubusercontent.com/80187628/147920944-eeae0bd3-35b9-4043-97f7-e1d72f873e93.png)
This is Screenshot of my browser, as you see the Google works right, I have to downlaod it from the depository from github, thank for your answer.

**Comment by danagbemava-nc** [comment] 2022-01-03 10:41
Hi @ninagon666, can you right-click on the page and select `Inspect Element` then navigate to the console, so that we know what error you're having in your console?

**Comment by ninagon666** [comment] 2022-01-03 10:46
![image](https://user-images.githubusercontent.com/80187628/147922099-205ef435-bf21-42c5-912c-958df07d8b5d.png)

**Comment by danagbemava-nc** [comment] 2022-01-03 11:02
It looks like there are issues fetching certain scripts, specifically `jquery`, probably due to your region. 

This looks like it needs further investigation.

**Comment by ninagon666** [comment] 2022-01-03 11:23
All right, thank for your answer.

**Comment by MiraMarshall** [comment] 2022-10-04 14:35
Closing because the issue could not be reproduced.

**Closed by MiraMarshall** 2022-10-04 14:35 UTC
Labels: p2-medium, e1-hours, can't reproduce
