### ISSUE TITLE
'Mock dependencies using Mockito' page issue - not null-safety adapted

### ISSUE THREAD

**Issue by pablo384** [flutter/website#5497] opened 2021-03-16 19:32 UTC
Page URL: https://flutter.dev/docs/cookbook/testing/unit/mocking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description of issue:
The handbook throws an error, is not null-safety adapted.

`00:03 +0 -1: fetchPost returns a Post if the http call completes successfully [E]                                                                 
  type 'Null' is not a subtype of type 'Future<Response>'
  package:http/src/client.dart 42:20   MockClient.get
  test/controllers/testing.dart 37:16  main.<fn>.<fn>
  test/controllers/testing.dart 31:68  main.<fn>.<fn>
  
00:03 +0 -2: fetchPost throws an exception if the http call completes with an error [E]                                                           
  Bad state: Cannot call `when` within a stub response
  package:mockito/src/mock.dart 1084:5  when
  test/controllers/testing.dart 48:7    main.<fn>.<fn>
  
00:03 +0 -2: Some tests failed.`

**Comment by sfshaza2** [comment] 2021-03-16 19:48
Duplicate of https://github.com/flutter/website/issues/5488. Closing.

**Closed by sfshaza2** 2021-03-16 19:48 UTC
