### ISSUE TITLE
[PAGE ISSUE]: 'Windows install'

### ISSUE THREAD

**Issue by AIMMOTH** [flutter/website#6689] opened 2022-01-16 07:14 UTC
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

> flutter channel stable
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ...
Expanding downloaded archive...
Remove-Item : Cannot remove item C:\Users\...\Documents\Programmering\Program\flutter\bin\cache\dart-sdk-windows-x64.z
ip: Åtkomst till sökvägen C:\Users\...\Documents\Programmering\Program\flutter\bin\cache\dart-sdk-windows-x64.zip neka
s.
At C:\Users\...\Documents\Programmering\Program\flutter\bin\internal\update_dart_sdk.ps1:94 char:1
+ Remove-Item $dartSdkZip
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\...\D...windows-x64.zip:FileInfo) [Remove-Item], Unauthoriz
   edAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Error: Unable to update Dart SDK. Retrying...

Waiting for 1 seconds, press CTRL+C to quit ...

### Additional context

Running with either command line or powershell, w/o admin rights. Same error

**Comment by danagbemava-nc** [comment] 2022-01-18 12:39
Hi @AIMMOTH, at what point in the installation process did you run into this issue?

**Comment by AIMMOTH** [comment] 2022-01-24 06:57
When I tried to change channel to master and also when I tried to change back to stable. Then I uninstalled everything, restarted, tried again to install but same error. Lowering UAC didn't matter either.

**Comment by danagbemava-nc** [comment] 2022-01-24 12:56
Did you run `flutter upgrade` when you switched channels?

**Comment by AIMMOTH** [comment] 2022-01-28 14:21
Hello, running Windows PowerShell 
`> flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ...
Expanding downloaded archive...
Remove-Item : Cannot remove item C:\Users\...\Documents\Programmering\Program\flutter\bin\cache\dart-sdk-windows-x64.zip: Åtkomst till sökvägen C:\Users\...\Documents\Programmering\Program\flutter\bin\cache\dart-sdk-windows-x64.zip nekas.
At C:\Users\...\Documents\Programmering\Program\flutter\bin\internal\update_dart_sdk.ps1:94 char:1
+ Remove-Item $dartSdkZip
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\...\D...windows-x64.zip:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Error: Unable to update Dart SDK. Retrying...

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? y`

**Comment by AIMMOTH** [comment] 2022-01-28 14:22
![bild](https://user-images.githubusercontent.com/5928807/151563170-0de41848-4cb9-4e5a-809e-eb280fd5f8e9.png)

**Comment by danagbemava-nc** [comment] 2022-01-31 11:23
Hi @AIMMOTH, where is flutter installed on your system? Can you provide the path?

**Comment by AIMMOTH** [comment] 2022-02-10 09:27
I've installed in my personal folder C:\Users\...\Documents\Programmering\Program\flutter

**Comment by danagbemava-nc** [comment] 2022-02-10 10:23
Hi @AIMMOTH, can you move it to a different directory, maybe `C:\src\`, and see if it makes any difference?

**Comment by AIMMOTH** [comment] 2022-02-19 10:45
It seems to work.
![bild](https://user-images.githubusercontent.com/5928807/154797634-92141084-d379-4a66-9ac2-4e013db991cb.png)

But I must say, the instructions was to install on your own user
![bild](https://user-images.githubusercontent.com/5928807/154797610-d6226a0f-38cd-40f1-93ee-07f96865e313.png)

**Comment by danagbemava-nc** [comment] 2022-02-21 13:42
Hi @AIMMOTH, it doesn't explicitly say that.  That directory is only used as an example. But I can see how it that may be misunderstood. We may need to improve the wording on that side.

**Comment by micpap25** [comment] 2022-03-31 14:38
Hi @danagbemava-nc, I'm planning to attempt to fix this issue; what is the root cause of the problem? That Flutter should not be installed to a user directory? Thank you

**Comment by danagbemava-nc** [comment] 2022-04-01 10:31
Hi @micpap25, it seems like there was an issue with resolving his path, it looks like the user name had some special characters. I think we can make a recommendation that they install it in a path that doesn't contain any special character or spaces. 

Personally, on windows, I usually use something like `C:\src\flutter`, so I don't run into issues with how windows handles long file names and the like.

**Closed** 2022-04-04 17:58 UTC
Labels: p3-low, e1-hours
