### ISSUE TITLE
'Store key-value data on disk' page issue

### ISSUE THREAD

**Issue by moweiran** [flutter/website#4580] opened 2020-09-06 04:28 UTC
Page URL: https://flutter.dev/docs/cookbook/persistence/key-value.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/key-value.md

Description of issue:

// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SharedPreferences Demo',
      home: SharedPreferencesDemo(),
    );
  }
}

class SharedPreferencesDemo extends StatefulWidget {
  SharedPreferencesDemo({Key key}) : super(key: key);

  @override
  SharedPreferencesDemoState createState() => SharedPreferencesDemoState();
}

class SharedPreferencesDemoState extends State<SharedPreferencesDemo> {
  Future<SharedPreferences> _prefs = SharedPreferences.getInstance();
  Future<int> _counter;

  Future<void> _incrementCounter() async {
    final SharedPreferences prefs = await _prefs;
    final int counter = (prefs.getInt('counter') ?? 0) + 1;

    setState(() {
      _counter = prefs.setInt("counter", counter).then((bool success) {
        return counter;
      });
    });
  }

  @override
  void initState() {
    super.initState();
    _counter = _prefs.then((SharedPreferences prefs) {
      return (prefs.getInt('counter') ?? 0);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("SharedPreferences Demo"),
      ),
      body: Center(
          child: FutureBuilder<int>(
              future: _counter,
              builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
                switch (snapshot.connectionState) {
                  case ConnectionState.waiting:
                    return const CircularProgressIndicator();
                  default:
                    if (snapshot.hasError) {
                      return Text('Error: ${snapshot.error}');
                    } else {
                      return Text(
                        'Button tapped ${snapshot.data} time${snapshot.data == 1 ? '' : 's'}.\n\n'
                        'This should persist across restarts.',
                      );
                    }
                }
              })),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

**Comment by aromalanil** [comment] 2020-09-06 06:43
@moweiran Could you please mention what the issue is? Is it something related to #4532 ?

**Comment by sfshaza2** [comment] 2020-09-10 07:35
Thanks for asking for clarification, @aromalanil!

Yes, @moweiran, this repo is where you can report problems with the flutter.dev docs or with the Flutter codelabs. Are you asking for support? Reporting a problem? Dealing with a Flutter SDK issue?

If you are asking for support, this is the wrong place. Please refer to the [Flutter community](https://flutter.dev/community) page for where you can get support. 

If this is related to [#4532](https://github.com/flutter/website/issues/4532), it's best to communicate on that issue, rather than open a new issue.

If this is a bug on the Flutter SDK, you can report that on the [flutter/flutter](https://github.com/flutter/flutter/issues) repo.

If I don't hear back from you in a day or two, I'll close this issue.

**Comment by sfshaza2** [comment] 2020-09-11 07:38
@moweiran, I'm closing this. Please re-open and clarify if it does apply to the docs on flutter.dev. Thx!

**Closed by sfshaza2** 2020-09-11 07:38 UTC
Labels: needs-info
