### ISSUE TITLE
Revise 'An introduction to unit testing' page to focus on `flutter_test` rather than `test` package.

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2837] opened 2019-07-18 03:07 UTC
Page URL: https://docs.flutter.dev/cookbook/testing/unit/introduction
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/introduction.md

Description of issue:

The beginning of the page says:

> The `test` package provides the core framework for writing unit tests, and the `flutter_test` package provides additional utilities for testing widgets.

But the rest of page fails to expose what's the difference between the `test` and `flutter_test` packages. After a short search I could find that `flutter_test` is built on top of the `test` package, which makes me wonder, why this Flutter cookbook suggest to add only a `test` package dependency then?

**Comment by sfshaza2** [comment] 2019-07-23 22:33
@brianegan, can you comment?

**Comment by atsansone** [comment] 2023-05-23 22:45
This issue should be handled at the same time as https://github.com/flutter/website/issues/5371.

**Comment by atsansone** [comment] 2023-05-23 22:48
This is a duplicate of https://github.com/flutter/website/issues/5372. Closing.

**Closed by atsansone** 2023-05-23 22:48 UTC
Labels: duplicate, p2-medium, cookbook, e1-hours, from:page-issue, testing
