### ISSUE TITLE
'Codelabs' page issue: Sidebar renders shortcuts and other text

### ISSUE THREAD

**Issue by Luckey-Elijah** [flutter/website#4613] opened 2020-09-15 17:49 UTC
Page URL: https://flutter.dev/docs/codelabs/
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/index.md

Description of issue: I'm on safari and I'm browsing the code labs then notice the sidebar:

<img width="1472" alt="Flutter-Codelab-display" src="https://user-images.githubusercontent.com/38171761/93246089-3cf49280-f75a-11ea-802d-4a86572dd523.png">

**Comment by JuYeong0413** [comment] 2020-09-16 09:11
duplicate of #4477
Could you please provide information about your platform, OS version, `flutter doctor` output? It would be helpful for the team to solve this issue.

**Comment by Luckey-Elijah** [comment] 2020-09-16 16:17
Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by sfshaza2** [comment] 2020-09-16 18:33
Thanks for that info, @Luckey-Elijah! We have been getting reports of this issue, as you can see on issue https://github.com/flutter/website/issues/4477. We believe that the fonts aren't being loaded correctly, but we don't know why. It seems to only be an issue in certain locales.

I'm closing this issue. Please continue any further discussion on the main bug page.

**Closed by sfshaza2** 2020-09-16 18:33 UTC
