### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by odegirmenci** [flutter/website#6864] opened 2022-03-01 13:53 UTC
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

http://www.websocket.org/ 

SERVICE NO LONGER AVAILABLE

**Comment by danagbemava-nc** [comment] 2022-03-02 11:38
Duplicate of #6382

**Closed by danagbemava-nc** 2022-03-02 11:38 UTC
Labels: in triage
