### ISSUE TITLE
Snippet tool b0rks on `tfserving-flutter` codelab files. This is blocking updating the website's codelab snippets.

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#7071] opened 2022-04-26 07:52 UTC
### Describe the problem

Attempting to run `./tool/refresh-code-excerpts.sh` on an up to date checkout of the `flutter/codelabs` git submodule results in the following:

```console
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab3/mm_update_spam_savedmodel/123/variables/variables.data-00000-of-00001:

FormatException: Unexpected extension byte (at offset 3)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab3/mm_update_spam_savedmodel/123/variables/variables.index:

FormatException: Unexpected extension byte (at offset 45)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab3/mm_update_spam_savedmodel/123/saved_model.pb:

FormatException: Unexpected extension byte (at offset 3)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab3/mm_update_spam_savedmodel/123/keras_metadata.pb:

FormatException: Missing extension byte (at offset 2)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab1/mm_spam_savedmodel/123/variables/variables.index:

FormatException: Unexpected extension byte (at offset 45)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab1/mm_spam_savedmodel/123/variables/variables.data-00000-of-00001:

FormatException: Unexpected extension byte (at offset 0)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab1/mm_spam_savedmodel/123/saved_model.pb:

FormatException: Missing extension byte (at offset 4)
[SEVERE] code_excerpter:code_excerpter on examples/codelabs/tfserving-flutter/codelab1/mm_spam_savedmodel/123/keras_metadata.pb:

FormatException: Missing extension byte (at offset 2)
```

### Expected fix

The snippet update tool should handle data files without losing it's lunch.

**Comment by khanhnwin** [comment] 2022-04-26 17:03
Related: #7001 has more details on the failure. @johnpryan I think you were going to look into this? Please let me know if I can help!

**Comment by domesticmouse** [comment] 2022-04-26 21:19
Actually this is a straight dupe of #7001

**Comment by parlough** [comment] 2022-04-27 00:23
Duplicate of https://github.com/flutter/website/issues/7001

**Closed by parlough** 2022-04-27 00:23 UTC
Labels: infrastructure, p1-high
