### ISSUE TITLE
'Pass arguments to a named route' page issue

### ISSUE THREAD

**Issue by NazarKalytiuk** [flutter/website#4014] opened 2020-04-29 23:22 UTC
Page URL: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigate-with-arguments.md

Description of issue:
An example not working
![image](https://user-images.githubusercontent.com/16141974/80656267-6ce01980-8a89-11ea-9209-1d66d1c42244.png)

**Comment by sfshaza2** [comment] 2020-04-30 15:32
I am able to reproduce this issue. Can you look at this, @johnpryan?

**Comment by RedBrogdon** [comment] 2020-04-30 21:21
Thanks for letting us know. @domesticmouse is investigating.

**Comment by domesticmouse** [comment] 2020-05-01 06:21
Looks like running DartPad's Flutter on the Beta channel fixes this issue.

@timsneath and @zoeyfan looks like I need to move DartPad to running Flutter channel beta to better reflect the API documentation it is embedded in.

**Comment by domesticmouse** [comment] 2020-05-01 20:44
I believe this is now fixed. Thanks for the report @NazarKalytiuk!

**Closed by domesticmouse** 2020-05-01 20:44 UTC
Labels: e1-hours, infrastructure, p1-high
