### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by pranayyy** [flutter/website#2940] opened 2019-08-27 12:31 UTC
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:

Document is outdated after installing insted of flutter " flutter-master" and flutter doctor is not recoginzed by cmd

**Comment by sfshaza2** [comment] 2019-09-17 20:19
Can't reproduce. Closing..

**Closed by sfshaza2** 2019-09-17 20:19 UTC
Labels: e1-hours, p1-high
