### ISSUE TITLE
Homepage issue on mobile

### ISSUE THREAD

**Issue by chalin** [flutter/website#3276] opened 2019-11-20 16:15 UTC
Note sure when this issue arose, but currently our homepage doesn't quite play well on mobile (e.g., content can shift left-right, but that shouldn't happen):

> <img src="https://user-images.githubusercontent.com/4140793/69256102-f1e41000-0b86-11ea-8045-e57f1280626e.png" width=300>

Related: #1951

**Comment by legalcodes** [comment] 2019-11-20 19:12
I was able to reproduce this via Chrome dev tools in the following dimensions:
- iPhone5/SE (320x568) 
- iPhone 6/7/8 (320x568)

FWIW I haven't been able to reproduce this on any physical devices yet (tried pixel 3, iPhone 6)

**Comment by sampathbalivada** [comment] 2019-11-22 20:01
Was able to replicate this. Seems like its an issue when the width is below 400.

**Comment by arps18** [comment] 2020-05-07 04:57
@legalcodes I would like to work on it!

**Comment by danagbemava-nc** [comment] 2022-05-04 12:51
Closing this in favor of #7094 since the website has gone through some changes since this issue was filed.

**Closed by danagbemava-nc** 2022-05-04 12:51 UTC
Labels: p1-high, e1-hours, mobile
