### ISSUE TITLE
[PAGE ISSUE]: 'State management'

### ISSUE THREAD

**Issue by VitaliyPtitsyn** [flutter/website#7096] opened 2022-05-05 08:28 UTC
### Page URL

https://docs.flutter.dev/development/data-and-backend/state-mgmt/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/state-mgmt/index.md

### Describe the problem

No content

**Comment by danagbemava-nc** [comment] 2022-05-05 10:30
Duplicate of #6758

**Closed by danagbemava-nc** 2022-05-05 10:30 UTC
Labels: in triage
