### ISSUE TITLE
'Display a snackbar' page issue

### ISSUE THREAD

**Issue by dougclarknc** [flutter/website#5241] opened 2021-02-01 16:48 UTC
Page URL: https://flutter.dev/docs/cookbook/design/snackbars.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/snackbars.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

Update Scaffold.of(context).showSnackbar from deprecated usage to current ScaffoldMessenger.of(context).showSnackBar useage?

**Comment by MrBirb** [comment] 2021-02-11 12:41
Duplicate of #4920

**Closed** 2021-02-11 14:06 UTC
