### ISSUE TITLE
Flutter install pages 404 Not found

### ISSUE THREAD

**Issue by frankcheng2020** [flutter/website#10160] opened 2024-02-16 06:57 UTC
### Page URL

https://docs.flutter.dev/release/whats-new

### Describe the problem

Flutter install](https://github.com/get-started/install) pages

404 Not  found.

Just let you know.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment] 2024-02-16 10:38
Thanks for the report! Closing this as a duplicate of https://github.com/flutter/website/issues/10158. Please follow up on it for further updates.

**Closed by huycozy** 2024-02-16 10:38 UTC
Labels: st.triage.triage-team, from.page-issue
