### ISSUE TITLE
Update tutorial on 'Take a picture using the camera' page

### ISSUE THREAD

**Issue by devabhishekpal** [flutter/website#5109] opened 2020-12-19 05:36 UTC
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:

I think the tutorial isn't updated with the latest version of the Camera Plugin, since the _controller.takePicture(path) gives an error for **path** argument telling that it takes 0 arguments. Also there have been a few changes in the newer version.
Kindly do check.

**Comment by sfshaza2** [comment] 2021-01-08 00:00
@johnpryan, can you check or delegate?

**Comment by johnpryan** [comment] 2021-01-08 00:33
This is correct, [`takePicture`](https://pub.dev/documentation/camera/latest/camera/CameraController/takePicture.html) no longer takes a path, so this needs to be fixed.

**Comment by VarunSAthreya** [comment] 2021-01-09 20:21
If the issue is still open I would like to work on it.

**Comment by piedcipher** [comment] 2022-09-19 18:25
Docs are already fixed! Good to close?

**Comment by atsansone** [comment] 2023-05-24 17:19
Fixed. Closing.

**Closed by atsansone** 2023-05-24 17:19 UTC
Labels: p2-medium, cookbook, e2-days, from:page-issue
