### ISSUE TITLE
'윈도우에서 설치' page issue

### ISSUE THREAD

**Issue by withligt** [flutter/website#6453] opened 2021-11-10 06:10 UTC
Page URL: https://flutter-kr.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:  SDK download button is failed

**Comment by danagbemava-nc** [comment] 2021-11-10 09:40
Duplicate of #5942

**Closed by danagbemava-nc** 2021-11-10 09:40 UTC
Labels: in triage
