### ISSUE TITLE
[PAGE ISSUE]: 'Flutter documentation'

### ISSUE THREAD

**Issue by nayeemtby** [flutter/website#7283] opened 2022-06-18 10:16 UTC
### Page URL

https://docs.flutter.dev/

### Page source

https://github.com/flutter/website/tree/main/src/index.md

### Describe the problem

Add dark mode.

### Expected fix

A button to switch to darkmode.

### Additional context

Hard to read code snippets for color contrast in some screens. And too bright to read docs at night.

**Comment by danagbemava-nc** [comment] 2022-06-20 11:55
Closing this as a duplicate of https://github.com/flutter/website/issues/3632

**Closed by danagbemava-nc** 2022-06-20 11:55 UTC
Labels: in triage
