### ISSUE TITLE
[PAGE ISSUE]: 'Ads support for Flutter'

### ISSUE THREAD

**Issue by zoeyfan** [flutter/website#6540] opened 2021-12-07 20:04 UTC
### Page URL

https://docs.flutter.dev/ads/

### Page source

https://github.com/flutter/website/tree/main/src/ads/index.md

### Describe the problem

This page contains outdated information.

I just submitted some changes to this site to reflect Ads being launched to GA. However, it occurred to me that we now have a new monetization page flutter.dev/monetization. 

Can we delete flutter.dev/ads, and redirect the link to flutter.dev/monetization? 

Thanks,
Zoey

### Expected fix

Can we delete flutter.dev/ads, and redirect the link to flutter.dev/monetization?

**Comment by danagbemava-nc** [comment] 2021-12-08 10:14
Hi @zoeyfan, looks like you've already filed this request in https://github.com/flutter/website/issues/6510. 

Closing this as a duplicate of #6510. 

Thank you

**Closed by danagbemava-nc** 2021-12-08 10:14 UTC
Labels: in triage
