### ISSUE TITLE
Issue from website page Building a form with validation

### ISSUE THREAD

**Issue by franklinharper** [flutter/website#1301] opened 2018-09-24 23:25 UTC
From URL: https://flutter.io/cookbook/forms/validation/

The example doesn't show how to access the data from the Form.

**Comment by Sfshaza** [comment] 2018-09-24 23:28
@brianegan

**Comment by Sfshaza** [comment] 2018-10-02 04:50
Duplicate of https://github.com/flutter/website/issues/1300.

Closing

**Closed as completed by Sfshaza** 2018-10-02 04:50 UTC
