### ISSUE TITLE
Work with WebSockets article needs a url update

### ISSUE THREAD

**Issue by mirkancal** [flutter/website#2780] opened 2019-06-23 17:28 UTC
ws://echo.websocket.org should be wss://echo.websocket.org in the article in order to Complete Example to work.

https://flutter.dev/docs/cookbook/networking/web-sockets#complete-example

**Comment by brianegan** [comment] 2019-06-25 14:25
Hey there -- just tested the example on a new Flutter project and it seems to be working as intended. Is the example failing on your end?

**Comment by sfshaza2** [comment] 2020-03-25 01:02
Closing.

**Closed by sfshaza2** 2020-03-25 01:02 UTC
Labels: cookbook, e0-minutes, p2-medium, waitingForCustomerResponse
