### ISSUE TITLE
'윈도우에서 설치' page issue

### ISSUE THREAD

**Issue by randomcanaries** [flutter/website#5942] opened 2021-06-21 02:18 UTC
Page URL: https://flutter-kr.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: not working Flutter SDK download link

**Comment by micpap25** [comment] 2021-06-21 13:18
![image](https://user-images.githubusercontent.com/34077605/122768505-a8cbd480-d271-11eb-9a19-ff0f0feed503.png)

**Comment by sfshaza2** [comment] 2021-07-15 18:40
@micpap25, do you know what this bug is about? Which language is this? (I can't search on the text as this seems to be an image.)

**Comment by micpap25** [comment] 2021-07-15 21:08
I was taking a screenshot of the page. 

When you hover over the "failed" link, you can see that it just links to the current page, instead of a download for Flutter. I'm not sure how to edit the Korean site for Flutter, but it seems that the link on that version of the site is messed up and should be changed so it actually points to a version of Flutter.

**Comment by danagbemava-nc** [comment] 2021-11-10 09:54
@sfshaza2, it looks like the request to https://storage.googleapis.com/flutter_infra/releases/releases_windows.json is being blocked so it is unable to fetch the SDKS. The issue is on the rest of the installation pages as well. 

![Screenshot 2021-11-10 at 09 47 16](https://user-images.githubusercontent.com/88313112/141090696-b4e1495a-abd5-4d23-929f-cec345d72093.png)

**Comment by danagbemava-nc** [comment] 2021-11-10 09:58
Closing as invalid, since the Korean website is community maintained

**Closed by danagbemava-nc** 2021-11-10 09:58 UTC
Labels: invalid

**Comment by sfshaza2** [comment] 2021-11-10 18:18
Thanks for following up, @micpap25 and @danagbemava-nc. Yes, the Korean site is community maintained. I'm not even sure who the contact is there.
