### ISSUE TITLE
Firebase for Flutter Codelab step 11

### ISSUE THREAD

**Issue by yash-1th** [flutter/website#4842] opened 2020-10-07 10:42 UTC
`.updateData()` is depricated use `.update()` instead.

While replacing a line of code with the following line of code use `.update()` instead of `.updateData()`

`onTap: () => record.reference.updateData({'votes': FieldValue.increment(1)})`

**Comment by maheshmnj** [comment] 2021-07-27 12:07
Hi @yash-1th , Thanks for filing the issue, Inorder for this issue to be actionable you need to provide a codelab link.
I suspect you are referring to this Codelab link: https://codelabs.flutter-io.cn/codelabs/flutter-firebase/index.html#9
If so, Unfortunately I could not find this piece of code 

```
onTap: () => record.reference.updateData({'votes': FieldValue.increment(1)})
``` 
This could be a possible duplicate of https://github.com/flutter/website/issues/4832

**Comment by yash-1th** [comment] 2021-07-29 05:20
Hi @maheshmnj, it has been 10 months. Even I can't find that particular piece of code now, may be someone might have changed the codelab. This issue and the issue you have mentioned is of same kind.

**Comment by maheshmnj** [comment] 2021-07-29 05:30
No worries, Thanks for the info probably it was moved.

**Comment by maheshmnj** [comment] 2021-07-29 05:53
Closing this issue as a duplicate of #4832, Feel free to comment if you disagree and I will reopen it. Thank you.

**Closed by maheshmnj** 2021-07-29 05:53 UTC
Labels: in triage
