### ISSUE TITLE
header is scrolling down when scrolling page downward

### ISSUE THREAD

**Issue by alihassan143** [flutter/website#8217] opened 2023-02-07 06:56 UTC
### Describe the problem

Website behaving strange when scrolling upward need to fix that behaviour

https://user-images.githubusercontent.com/71745182/217170196-8cfb4e9b-a1e6-4376-bb10-719a1cd751b6.mp4

### Expected fix

just need to fix the header when scrolling upward

**Comment by danagbemava-nc** [comment] 2023-02-07 10:31
Hi @alihassan143, is this on every page you visit, or is it on only specific pages?

**Comment by alihassan143** [comment] 2023-02-07 10:45
its happening on specific pages

**Comment by danagbemava-nc** [comment] 2023-02-07 13:22
Hi @alihassan143, kindly share some of those pages so we can investigate this. 

Also, what browser are you using and what version of said browser are you using?

Can you also check if you get any errors in your browser console?

**Comment by parlough** [comment] 2023-02-07 20:03
Thanks for the extra context. Are there any errors in the Chrome developer console?

Also, do you have any extensions which modify styles?

**Comment by alihassan143** [comment] 2023-02-08 04:07
No i am not using any extension for modifying styles
no i cannot see any particular error in console

**Comment by danagbemava-nc** [comment] 2023-02-08 10:52
Hi @alihassan143, are you scrolling with the trackpad or an external mouse? 
I looked at the page, but I just got a bouncing scroll effect and nothing as egregious as yours

**Comment by alihassan143** [comment] 2023-02-08 11:00
i am scrolling through external mouse and getting this behaviour on track pad its working fine

**Comment by danagbemava-nc** [comment] 2023-02-09 11:52
Thanks for the info. 

I can't reproduce this with my external mouse. @alihassan143 is this behavior consistent?

**Comment by alihassan143** [comment] 2023-02-09 12:02
No now this page is working fine i things its browser cache issue or network issue

**Comment by danagbemava-nc** [comment] 2023-02-09 13:52
Thanks for the info. I'll be closing this for now since it seemed like just an issue on your local system

**Closed by danagbemava-nc** 2023-02-09 13:52 UTC
Labels: design, in triage
