### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by jonzhou45** [flutter/website#2444] opened 2019-02-25 04:42 UTC
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
![image](https://user-images.githubusercontent.com/27979427/53314692-b2092a00-388d-11e9-9788-46d724b30fc1.png)

I have Git installed as well as Windows Powershell my computer is Windows 10.

**Comment by sfshaza2** [comment] 2019-03-06 05:21
Duplicate of https://github.com/flutter/website/issues/2460

Closing

**Closed by sfshaza2** 2019-03-06 05:21 UTC
