### ISSUE TITLE
'Flutter SDK releases' page issue

### ISSUE THREAD

**Issue by raghavan-mookiah** [flutter/website#4301] opened 2020-07-03 01:05 UTC
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue: Some programming literals or variables are 
<img width="1314" alt="Screenshot 2020-07-03 at 6 32 17 AM" src="https://user-images.githubusercontent.com/47385593/86421353-5fe4de00-bcf7-11ea-8065-eca456673b37.png">
 visible on the page refer the screenshot

**Comment by kwalrath** [comment] 2020-07-06 16:13
This looks like an issue with loading the images. Does reloading the page help?

**Comment by sfshaza2** [comment] 2020-07-14 17:59
@raghavan-mookiah, we can't reproduce this. Can you give us more information about your platform, OS version, etc? Without the ability to reproduce, we'll have to close this.

**Comment by sfshaza2** [comment] 2020-08-13 16:47
I'm closing this as a duplicate of Issue https://github.com/flutter/website/issues/4477. However, it would really help us if you could provide the output of `flutter doctor` so we could try to diagnose this.

**Closed by sfshaza2** 2020-08-13 16:47 UTC
Labels: can't reproduce, needs-info
