### ISSUE TITLE
'Adding a splash screen and launch screen to an Android app' page issue

### ISSUE THREAD

**Issue by chileshemartin** [flutter/website#3774] opened 2020-03-07 12:56 UTC
Page URL: https://flutter.dev/docs/development/ui/splash-screen/android-splash-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/splash-screen/android-splash-screen.md

Description of issue: The section for creating a custom splash screen is a bit vague. For example: where do I add that sample code and how do I invoke it? I'm I supposed to create a new file or add it to the MainActivity.kt
Also, the example only has a java guideline but when you create a new flutter application, there is only a kotlin file in android\app\src\main\kotlin\com\example\packagename\MainActivity.kt by default.

Kindly help..
![Screenshot (192)](https://user-images.githubusercontent.com/15169700/76143921-11467080-6084-11ea-838f-11014063b69b.png)

**Comment by sfshaza2** [comment] 2021-03-10 21:00
Duplicate of https://github.com/flutter/website/issues/3938

**Closed by sfshaza2** 2021-03-10 21:00 UTC
Labels: e1-hours, p2-medium
