### ISSUE TITLE
☂️ Updates for flavors page

### ISSUE THREAD

**Issue by MiraMarshall** [flutter/website#7979] opened 2022-12-22 19:58 UTC
https://docs.flutter.dev/deployment/flavors/

TODOs for flavors page:

- [ ] Add/reference an app sample with free/paid flavors. 
- [ ] Update screenshots to display free and paid flavors. 
- [ ] Update page to better follow google developer documentation style and formatting guidelines
- [ ] Organize all iOS content under a single header
- [ ] Better clarify meaning of "desired flavors" in Android documentation
- [ ] Better format explanation of options in `build.gradle` 
- [ ] Full copy edit of page

----
Covers:
- [ ] https://github.com/flutter/website/issues/8743
- [ ] https://github.com/flutter/website/issues/8746
- [ ] https://github.com/flutter/website/issues/8238
- [ ] https://github.com/flutter/website/issues/9309

**Comment by MiraMarshall** [comment] 2022-12-22 20:06
@jmagman

**Comment by jmagman** [comment] 2022-12-22 20:09
@MiraMarshall is this a duplicate of https://github.com/flutter/website/issues/4321?

**Comment by jmagman** [comment] 2022-12-22 20:10
Ah, no I see it's the follow-up TODOs from https://github.com/flutter/website/pull/7867.

**Comment by atsansone** [comment] 2024-01-18 19:51
Move to #9976

**Closed by atsansone** 2024-01-18 19:51 UTC
Labels: cl.duplicate, fix.quality, st.triage.ltw, meta.umbrella, dev.deployment, dev.flavors
