### ISSUE TITLE
The left column of Flutter website reported an error

### ISSUE THREAD

**Issue by gionchat** [flutter/website#6290] opened 2021-09-17 05:18 UTC
![image](https://user-images.githubusercontent.com/58280808/133728493-a0919fc8-4776-44d2-84a5-36e555d03efa.png)

**Comment by TahaTesser** [comment] 2021-09-17 12:53
Hi @gionchat 
Please check out  https://github.com/flutter/website/issues/6151#issuecomment-899950567
duplicate of https://github.com/flutter/website/issues/6151

**Closed by TahaTesser** 2021-09-17 12:53 UTC
Labels: in triage
