### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by anaszgh** [flutter/website#1909] opened 2018-12-06 06:01 UTC
Page URL: https://flutter.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description:
cannot download the sdk, keeps loading forever

**Comment by kwalrath** [comment] 2018-12-06 17:21
It works for me (in the western US). This might be something specific to your setup or location. Can you download other large files (this one's 321 MB)? Can you tell us where you're located?

**Comment by jonzhou45** [comment] 2019-02-25 04:08
I am having the same issue with this. 
The button starts from (loading..) then becomes (failed)

I also open up the Flutter SDK archive and it is still loading forever.

**Comment by cneilmon** [comment] 2019-04-25 11:50
hey! look at the comment here: https://github.com/flutter/website/issues/2595
seems its already working fine

**Comment by sfshaza2** [comment] 2020-04-23 02:32
Duplicate of https://github.com/flutter/website/issues/3982

**Closed by sfshaza2** 2020-04-23 02:32 UTC
Labels: can't reproduce, needs-info
